# Generated by Django 5.2.16 on 2026-09-25 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("handler_notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="seen_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="seen at"),
        ),
        migrations.AddField(
            model_name="note",
            name="seen_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seen_by_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="seen by",
            ),
        ),
    ]
