const nextConfig = require('../../next.config');
const { withKesaseteliSecurityHeaders } = require('../shared/src/config/csp');
const { i18n } = require('./next-i18next.config');
const { parsed: env } = require('dotenv').config({
  path: '../../../.env.kesaseteli-handler',
});

const trueEnv = ['true', '1', 'yes'];
const enableNewBetaUI = trueEnv.includes(
  (process.env.NEXT_PUBLIC_ENABLE_HANDLER_NEW_BETA_UI ?? 'false').toLowerCase()
);

module.exports = withKesaseteliSecurityHeaders(
  nextConfig({
    i18n,
    env,
    async redirects() {
      if (enableNewBetaUI) {
        // New Beta UI is enabled:
        // Forward legacy email links (/?id=xxx) generated by
        // handler_youth_application_processing_url() in the backend
        // to the new beta UI's application detail page.
        return [
          {
            source: '/',
            has: [{ type: 'query', key: 'id', value: '(?<id>[a-zA-Z0-9-]+)' }],
            destination: '/youth-applications/:id',
            permanent: false,
          },
        ];
      }
      // Legacy mode (NEXT_PUBLIC_ENABLE_HANDLER_NEW_BETA_UI is off):
      // Block access to all new beta UI routes by redirecting to /.
      // NOTE: The following pages must remain accessible in BOTH
      // modes and are intentionally NOT blocked here:
      //   /login, /create-application-without-ssn, /cookie-settings,
      //   /thankyou, /403, /404, /500
      return [
        { source: '/dashboard', destination: '/', permanent: false },
        {
          source: '/youth-applications/:id',
          destination: '/?id=:id',
          permanent: false,
        },
        {
          source: '/youth-applications/:path*',
          destination: '/',
          permanent: false,
        },
        {
          source: '/employer-applications/:path*',
          destination: '/',
          permanent: false,
        },
      ];
    },
    async rewrites() {
      if (enableNewBetaUI) {
        // Transparently serve the dashboard on / when new beta
        // UI is enabled. The browser URL stays as /.
        return {
          beforeFiles: [{ source: '/', destination: '/dashboard' }],
        };
      }
      return [];
    },
  })
);
