import logging
from datetime import datetime
from datetime import timezone as dt_timezone

from django.conf import settings
from django.utils import translation

from applications.enums import EmailTemplateType, EmployerApplicationStatus
from applications.models import EmployerSummerVoucher
from common.tests.factories import (
    EmployerSummerVoucherFactory,
    YouthApplicationFactory,
    YouthSummerVoucherFactory,
)

LOGGER = logging.getLogger(__name__)


class MockContextService:
    @staticmethod
    def get_mock_context(template_type: str, language: str = "fi") -> dict:
        """
        Generate a mock context dictionary for the given template type using Factories.
        """
        with translation.override(language):
            if template_type == EmailTemplateType.ACTIVATION:
                return MockContextService._get_activation_context(language)
            elif template_type == EmailTemplateType.ADDITIONAL_INFO_REQUEST:
                return MockContextService._get_additional_info_context(language)
            elif template_type == EmailTemplateType.PROCESSING:
                return MockContextService._get_processing_context(language)
            elif template_type == EmailTemplateType.YOUTH_SUMMER_VOUCHER:
                return MockContextService._get_youth_summer_voucher_context(language)
        return {}

    @staticmethod
    def _get_activation_context(language):
        YouthApplicationFactory.build(language=language)
        # Mocking the activation link since we don't have a request easily available
        activation_link = f"{settings.YOUTH_URL}/{language}/activate?id=mock-uuid"
        return {"activation_link": activation_link}

    @staticmethod
    def _get_additional_info_context(language):
        # Same context variable as activation
        return MockContextService._get_activation_context(language)

    @staticmethod
    def _get_processing_context(language):
        app = YouthApplicationFactory.build(language=language)
        processing_link = f"https://handler.hel.fi/process/{app.pk}"
        return {
            "first_name": app.first_name,
            "last_name": app.last_name,
            "school": app.school,
            "postcode": app.postcode,
            "phone_number": app.phone_number,
            "email": app.email,
            "processing_link": processing_link,
        }

    @staticmethod
    def _get_youth_summer_voucher_context(language):
        # We need a full voucher for this
        voucher = YouthSummerVoucherFactory.build(
            youth_application=YouthApplicationFactory.build(language=language)
        )
        # Ensure year is set (factories might default to current time)
        # We need to manually invoke properties if they are not fields

        return {
            "first_name": voucher.youth_application.first_name,
            "last_name": voucher.youth_application.last_name,
            "summer_voucher_serial_number": voucher.summer_voucher_serial_number,
            "postcode": voucher.youth_application.postcode,
            "school": voucher.youth_application.school,
            "phone_number": voucher.youth_application.phone_number,
            "email": voucher.youth_application.email,
            "year": voucher.year,
            "voucher_value_with_euro_sign": voucher.voucher_value_with_euro_sign,
            "summer_job_period_localized_string": (
                voucher.summer_job_period_localized_string
            ),
            "employer_summer_voucher_application_end_date_localized_string": (
                voucher.employer_summer_voucher_application_end_date_localized_string
            ),
            "min_work_hours": voucher.min_work_hours,
            "min_work_compensation_with_euro_sign": (
                voucher.min_work_compensation_with_euro_sign
            ),
        }


class TalpaExportMockService:
    @staticmethod
    def ensure_talpa_export_test_applications(target_count: int) -> int:
        """
        Ensure at least `target_count` EmployerSummerVouchers are ready for
        Talpa export (unhandled, for_export queryset). Creates the difference
        if fewer exist.

        Returns the number of vouchers created.
        """
        existing = EmployerSummerVoucher.objects.unhandled().for_export().count()
        to_create = max(0, target_count - existing)
        if to_create == 0:
            LOGGER.info(
                "ensure_talpa_export_test_applications: %d/%d already exist, "
                "nothing to create.",
                existing,
                target_count,
            )
            return 0

        timestamp = datetime.now(dt_timezone.utc).strftime("%Y%m%d-%H%M%S")
        for i in range(to_create):
            label = f"cronjob-{timestamp}-{i + 1}"
            EmployerSummerVoucherFactory(
                application__status=EmployerApplicationStatus.SUBMITTED,
                application__company__name=f"Autogenerated Talpa Co {label}",
                is_exported=False,
                # Break the RelatedFactory cycle: AcceptedYouthApplicationFactory
                # would normally fire a RelatedFactory to create a second
                # YouthSummerVoucher for the same YouthApplication, causing an
                # IntegrityError (OneToOneField). Passing youth_summer_voucher=None
                # disables it — same pattern used by YouthSummerVoucherFactory itself.
                youth_summer_voucher__youth_application__youth_summer_voucher=None,
                youth_summer_voucher__youth_application__first_name="Autogenerated",
                youth_summer_voucher__youth_application__last_name=f"Talpa {timestamp}",
            )

        LOGGER.info(
            "ensure_talpa_export_test_applications: created %d voucher(s) "
            "(total target: %d).",
            to_create,
            target_count,
        )
        return to_create
