# =======================================
FROM registry.access.redhat.com/ubi9/nodejs-24-minimal AS distbase
# =======================================

USER root

# Install ca-certificates so that Sentry can upload source maps
RUN microdnf update -y && microdnf install -y ca-certificates gzip && microdnf clean all

# Install pnpm
RUN npm install -g pnpm@11.5.0

# =============================
FROM distbase AS appbase
# =============================

USER root

# Build ARGS
ARG PROJECT
ARG FOLDER

WORKDIR /app

RUN groupadd --gid 1000 default
RUN useradd --uid 1000 --gid default --create-home --shell /bin/bash default

# Install dependencies
COPY --chown=default:default package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY --chown=default:default $PROJECT/$FOLDER/package.json $PROJECT/$FOLDER/package.json
COPY --chown=default:default $PROJECT/shared/package.json* $PROJECT/shared/package.json
COPY --chown=default:default shared/package.json shared/package.json
RUN --mount=type=cache,target=/pnpm/store,sharing=locked pnpm install --store-dir /pnpm/store --frozen-lockfile

# Ensure the project's .next directory exist and is accessible
# so that the express server can access the files
RUN mkdir -p $PROJECT/$FOLDER/.next \
    && chown -R default:default $PROJECT/$FOLDER/.next \
    && chmod -R u=rwx,go=rx $PROJECT/$FOLDER/.next

# =============================
FROM appbase AS development
# =============================

# Create the directory with correct permissions for VSCode server
RUN mkdir -p /opt/app-root/src/.vscode-server && chown -R default:default /opt/app-root/src

# Copy all files
COPY --chown=default:default . .

# Use non-root user
USER default

# Set V8 max heap size to 2GB (default is 512MB)
# This prevents Docker Compose from crashing due to out of memory errors
ENV NODE_OPTIONS="--max_old_space_size=2048"

ARG PROJECT
ARG FOLDER

# Enable Turbopack for faster dev builds, see https://nextjs.org/docs/14/architecture/turbopack
#
# Next.js internally checks !!process.env.TURBOPACK in router-server.ts (not documented API),
# see https://github.com/vercel/next.js/blob/v14.2.32/packages/next/src/server/lib/router-server.ts#L135
# To disable, set TURBOPACK="" (empty string). Note: "0" or "false" won't work due to !! coercion
ARG TURBOPACK=1
ENV TURBOPACK=${TURBOPACK}

# Enable hot reload by default by polling for file changes.
#
# NOTE: Can be disabled by setting WATCHPACK_POLLING=false
#       if hot reload works on your system without polling to save CPU time.
ARG WATCHPACK_POLLING=true
ENV WATCHPACK_POLLING=${WATCHPACK_POLLING}

# Use non-root user
USER default
WORKDIR /app

# Copy all files
COPY --chown=default:default . .

ENV NEXT_TELEMETRY_DISABLED 1

# Bake package.json start command into the image
ENV DEV_START "pnpm --dir $PROJECT/$FOLDER dev"
CMD ["sh", "-c", "${DEV_START}"]
