module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  moduleNameMapper: {
    [`^shared\/(.*)$`]: '<rootDir>/shared/src/$1',
    [`^kesaseteli-shared\/(.*)$`]: '<rootDir>/kesaseteli/shared/src/$1',
    [`^kesaseteli/employer\/(.*)$`]: '<rootDir>/kesaseteli/employer/src/$1',
    [`^kesaseteli/youth\/(.*)$`]: '<rootDir>/kesaseteli/youth/src/$1',
    [`^kesaseteli/handler\/(.*)$`]: '<rootDir>/kesaseteli/handler/src/$1',
    [`^benefit/applicant\/(.*)$`]: '<rootDir>/benefit/applicant/src/$1',
    [`^benefit/handler\/(.*)$`]: '<rootDir>/benefit/handler/src/$1',
    [`^tet/admin\/(.*)$`]: '<rootDir>/tet/admin/src/$1',
    [`^tet/employer\/(.*)$`]: '<rootDir>/tet/employer/src/$1',
    [`^tet/youth\/(.*)$`]: '<rootDir>/tet/youth/src/$1',
    [`^tet/shared\/(.*)$`]: '<rootDir>/tet/shared/src/$1',
  },
  setupFilesAfterEnv: [
    '<rootDir>/shared/src/__tests_/utils/setupTests.ts',
    '<rootDir>benefit/applicant/test/i18n/i18n-test.ts',
    '<rootDir>benefit/handler/test/i18n/i18n-test.ts',
    '<rootDir>kesaseteli/employer/src/__tests__/utils/i18n/i18n-test.ts',
    '<rootDir>kesaseteli/youth/src/__tests__/utils/i18n/i18n-test.ts',
    '<rootDir>tet/admin/src/__tests__/utils/init-18n.ts',
  ],
  coveragePathIgnorePatterns: [
    '<rootDir>/kesaseteli/employer/src/pages/',
    '<rootDir>kesaseteli/shared/src/__tests__/utils/',
    '<rootDir>/youth/employer/src/pages/',
    '<rootDir>/benefit/applicant/src/pages/',
    '<rootDir>/benefit/handler/src/pages/',
    '<rootDir>/shared/src/server/next-server.js',
    '<rootDir>/shared/src/__tests__/component-apis/',
    '<rootDir>/shared/src/__tests__/utils/',
    '<rootDir>/tet/admin/src/pages/',
    '<rootDir>/tet/employer/src/pages/',
    '<rootDir>/tet/youth/src/pages/',
    '<rootDir>/tet/shared/src/__tests__/utils/',

  ],
  collectCoverageFrom: ['./**/*.{ts,tsx,js,jsx}'],
  testPathIgnorePatterns: ['__tests__/utils', 'component-apis'],
};
