name: yjdh-benefit
services:
  postgres:
    build:
      context: ./backend
      dockerfile: ./docker/finnish_postgres_17.Dockerfile
    restart: on-failure
    environment:
      POSTGRES_USER: benefit
      POSTGRES_PASSWORD: benefit
      POSTGRES_DB: benefit
      LC_COLLATE: "fi_FI.UTF-8"
      LC_CTYPE: "fi_FI.UTF-8"
    ports:
      - 127.0.0.1:5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: benefit-db

  backend:
    build:
      context: ./backend
      dockerfile: ./docker/benefit-ubi-arm.Dockerfile
      target: development
    env_file:
      - .env.benefit-backend
    environment:
      DATABASE_URL: postgres://benefit:benefit@benefit-db/benefit
      DATABASE_HOST: benefit-db.helsinki
    volumes:
      - ./backend/benefit:/app
      - ./backend/shared:/shared
    depends_on:
      - postgres
    container_name: benefit-backend

  local-proxy:
    depends_on:
      - postgres
      - backend
    build:
      context: ./localdevelopment/benefit/nginx
    container_name: benefit-local-proxy
    volumes:
      - ./localdevelopment/benefit/nginx/:/etc/nginx/
    ports:
      - 127.0.0.1:8000:8000

  mailpit:
    image: "axllent/mailpit:v1.21.4"
    ports:
      - 1025:1025
      - 8025:8025
    container_name: benefit-mailpit
    networks:
      - default

  clamav:
    image: clamav/clamav:latest
    container_name: benefit-clamav
    environment:
      CLAMAV_NO_LOGFILE: "true"
    volumes:
      - clamav_data:/var/lib/clamav
      - clamav_logs:/var/log/clamav
    ports:
      - "3310:3310"
    networks:
      - default

  clamav-rest-api:
    image: benzino77/clamav-rest-api
    container_name: benefit-clamav-rest-api
    environment:
      NODE_ENV: production
      APP_PORT: 8080
      APP_FORM_KEY: attachment_file
      CLAMD_IP: clamav
      APP_MAX_FILE_SIZE: 26214400
    ports:
      - "8080:8080"
    depends_on:
      - clamav
    command:
      [
        "/usr/wait-for-it.sh",
        "clamav:3310",
        "--timeout=30",
        "--",
        "node",
        "src/app.js",
      ]
    volumes:
      - ./backend/docker/arm/tools/wait-for-it.sh:/usr/wait-for-it.sh
    networks:
      - default

volumes:
  pgdata:
    driver: local
  clamav_data:
    driver: local
  clamav_logs:
    driver: local

networks:
  default:
    name: helsinki
