import json

from django.http import HttpResponse, JsonResponse
from django.views.generic import View

from postings.models import TetPostingTemp


class MockCreateOrReadView(View):
    http_method_names = ["get", "post"]

    def get(self, request):
        if request.user.is_authenticated:
            postings = TetPostingTemp.objects.all()
            return JsonResponse([json.loads(p.data) for p in postings], safe=False)
        else:
            return HttpResponse("Unauthorized", status=401)

    def post(self, request):
        if request.user.is_authenticated:
            # TODO do we need validation?
            body = request.body.decode("utf-8")
            data = json.loads(body)

            # Using user's email as the "owner" of the TET posting
            # In production version user sees only their own or their organization's postings
            p = TetPostingTemp(owner=request.user.email, data=json.dumps(data))
            p.save()

            # Save autogenerated id as part of data
            data["id"] = str(p.id)
            p.data = json.dumps(data)
            p.save()

            return JsonResponse(data)
        else:
            return HttpResponse("Unauthorized", status=401)
