# Base SonarQube configuration for City of Helsinki Frontend projects
sonar.projectKey = City-of-Helsinki_yjdh-helsinkilisa-shared
sonar.organization=city-of-helsinki
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.inclusions=src/**/*
sonar.exclusions= \
  **/__mocks__/**/*, \
  **/__snapshots__/*, \
  **/*.d.ts, \
  **/*.sc.ts, \
  src/types/**/*, \
  src/utils/test-utils/**/*

sonar.test.inclusions= \
  src/**/__tests__/**/*, \
  src/**/*.test.js, \
  src/**/*.test.ts, \
  src/**/*.test.jsx, \
  src/**/*.test.tsx

# helsinkilisa-shared specific
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S3735
sonar.issue.ignore.multicriteria.e1.resourceKey=*.ts,*.tsx
