# Generated by Django 3.2.4 on 2021-06-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="manual_city",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="manual city"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="manual_company_form",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="manual company form"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="manual_industry",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="manual industry"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="manual_postcode",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="manual postcode"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="manual_street_address",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="manual street address"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=256, verbose_name="city"),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_form",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="company form"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, max_length=256, verbose_name="industry"),
        ),
        migrations.AlterField(
            model_name="company",
            name="postcode",
            field=models.CharField(blank=True, max_length=256, verbose_name="postcode"),
        ),
        migrations.AlterField(
            model_name="company",
            name="street_address",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="street address"
            ),
        ),
    ]
