# Generated by Django 3.2.4 on 2021-06-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0002_eauthorizationprofile"),
        ("companies", "0002_company_optional_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="eauth_profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company",
                to="oidc.eauthorizationprofile",
                verbose_name="eauthorization profile",
            ),
        ),
    ]
