# Generated by Django 5.1.15 on 2026-02-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_alter_company_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("company", "Company"),
                    ("association", "Association"),
                    ("parish", "Parish"),
                    ("other", "Other"),
                ],
                max_length=64,
                verbose_name="organization type",
            ),
        ),
    ]
