# Generated by Django 5.1.15 on 2026-02-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_company_organization_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="business_id",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="business id"
            ),
        ),
    ]
