# Generated by Django 5.1.15 on 2026-02-05 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0008_make_company_business_id_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
    ]
