# Generated by Django 5.1.15 on 2026-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0010_populate_company_timestamps"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="company_name_idx"),
        ),
    ]
