# Generated by Django 3.2.4 on 2021-09-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="business_id",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="business id"
            ),
        ),
    ]
