# Generated by Django 3.2.4 on 2022-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_unique_company_business_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_form_code",
            field=models.IntegerField(
                default=16, verbose_name="YTJ type code for company form"
            ),
            preserve_default=False,
        ),
    ]
