# Generated by Django 4.2.11 on 2024-09-26 12:09

import common.localized_iban_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_localized_iban_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank_account_number',
            field=common.localized_iban_field.LocalizedIBANField(blank=True, include_countries=('FI',), max_length=34, use_nordea_extensions=False, verbose_name='bank account number'),
        ),
    ]
