# Generated by Django 5.2.12 on 2026-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_bank_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='industry (TOL code description)'),
        ),
    ]
