import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TET Job Search - Youth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          TET Job Search - Youth
        </h1>
      </main>
    </div>
  )
}

export default Home
