# Generated by Django 3.2.4 on 2021-06-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="employment_contract",
            field=models.TextField(
                blank=True, max_length=100, verbose_name="employment contract"
            ),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="payslip",
            field=models.TextField(blank=True, max_length=100, verbose_name="payslip"),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="employment_contract",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="employment contract"
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="payslip",
            field=models.FileField(blank=True, upload_to="", verbose_name="payslip"),
        ),
    ]
