# Generated by Django 3.2.4 on 2021-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_application_contact_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    (
                        "additional_information_requested",
                        "Additional information requested",
                    ),
                    (
                        "additional_information_provided",
                        "Additional information provided",
                    ),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("deleted_by_customer", "Deleted by customer"),
                ],
                default="draft",
                max_length=64,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    (
                        "additional_information_requested",
                        "Additional information requested",
                    ),
                    (
                        "additional_information_provided",
                        "Additional information provided",
                    ),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("deleted_by_customer", "Deleted by customer"),
                ],
                default="draft",
                max_length=64,
                verbose_name="status",
            ),
        ),
    ]
