# Generated by Django 3.2.4 on 2021-08-26 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_refactor_attachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "application",
                "verbose_name_plural": "applications",
            },
        ),
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "ordering": [
                    "-summer_voucher__created_at",
                    "attachment_type",
                    "-created_at",
                ],
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
            },
        ),
        migrations.AlterModelOptions(
            name="summervoucher",
            options={
                "ordering": ["-application__created_at", "ordering"],
                "verbose_name": "summer voucher",
                "verbose_name_plural": "summer vouchers",
            },
        ),
        migrations.AddField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="modified_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="time modified",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="modified_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="time modified",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="time created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="time modified"),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
    ]
