# Generated by Django 3.2.4 on 2021-08-30 09:43

from django.db import migrations


def delete_applications(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    Application.objects.all().delete()


class Migration(migrations.Migration):
    """
    Delete applications since the next migration (0009_add_application_user) will add the user ForeignKey for
    the appilcations and it is not possible to set a reasonable default value for that. Delete all applications
    since there is no use form them without an user.
    """

    dependencies = [
        ("applications", "0007_model_timestamps_and_ordering"),
    ]

    operations = [
        migrations.RunPython(delete_applications, migrations.RunPython.noop),
    ]
