# Generated by Django 3.2.4 on 2021-09-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_add_application_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalsummervoucher",
            old_name="summer_voucher_id",
            new_name="summer_voucher_serial_number",
        ),
        migrations.RenameField(
            model_name="summervoucher",
            old_name="summer_voucher_id",
            new_name="summer_voucher_serial_number",
        ),
        migrations.RemoveField(
            model_name="historicalsummervoucher",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="historicalsummervoucher",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="historicalsummervoucher",
            name="is_unnumbered_summer_voucher",
        ),
        migrations.RemoveField(
            model_name="historicalsummervoucher",
            name="unnumbered_summer_voucher_reason",
        ),
        migrations.RemoveField(
            model_name="historicalsummervoucher",
            name="work_postcode",
        ),
        migrations.RemoveField(
            model_name="summervoucher",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="summervoucher",
            name="contact_name",
        ),
        migrations.RemoveField(
            model_name="summervoucher",
            name="is_unnumbered_summer_voucher",
        ),
        migrations.RemoveField(
            model_name="summervoucher",
            name="unnumbered_summer_voucher_reason",
        ),
        migrations.RemoveField(
            model_name="summervoucher",
            name="work_postcode",
        ),
        migrations.AddField(
            model_name="application",
            name="language",
            field=models.CharField(
                choices=[("fi", "suomi"), ("sv", "svenska"), ("en", "english")],
                default="fi",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="language",
            field=models.CharField(
                choices=[("fi", "suomi"), ("sv", "svenska"), ("en", "english")],
                default="fi",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="employee_home_city",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="employee home city"
            ),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="employee_postcode",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="employee postcode"
            ),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="employment_description",
            field=models.TextField(blank=True, verbose_name="employment description"),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="employment_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="employment end date"
            ),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="employment_postcode",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="employment postcode"
            ),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="employment_salary_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="employment salary paid",
            ),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="employment_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="employment start date"
            ),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="employment_work_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="employment work hours",
            ),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="hired_without_voucher_assessment",
            field=models.CharField(
                blank=True,
                choices=[("yes", "yes"), ("no", "no"), ("maybe", "maybe")],
                help_text="Whether the employee would have been hired without a summer voucher.",
                max_length=32,
                null=True,
                verbose_name="hired without voucher assessment",
            ),
        ),
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="summer_voucher_exception_reason",
            field=models.CharField(
                blank=True,
                choices=[("9th_grader", "9th grader"), ("born_2004", "born 2004")],
                help_text="Special case of admitting the summer voucher.",
                max_length=256,
                verbose_name="summer voucher exception class",
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="employee_home_city",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="employee home city"
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="employee_postcode",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="employee postcode"
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="employment_description",
            field=models.TextField(blank=True, verbose_name="employment description"),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="employment_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="employment end date"
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="employment_postcode",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="employment postcode"
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="employment_salary_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="employment salary paid",
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="employment_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="employment start date"
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="employment_work_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="employment work hours",
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="hired_without_voucher_assessment",
            field=models.CharField(
                blank=True,
                choices=[("yes", "yes"), ("no", "no"), ("maybe", "maybe")],
                help_text="Whether the employee would have been hired without a summer voucher.",
                max_length=32,
                null=True,
                verbose_name="hired without voucher assessment",
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="summer_voucher_exception_reason",
            field=models.CharField(
                blank=True,
                choices=[("9th_grader", "9th grader"), ("born_2004", "born 2004")],
                help_text="Special case of admitting the summer voucher.",
                max_length=256,
                verbose_name="summer voucher exception class",
            ),
        ),
    ]
