# Generated by Django 3.2.4 on 2021-09-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_update_summer_voucher_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsummervoucher",
            name="is_exported",
            field=models.BooleanField(
                default=False,
                help_text="Has been exported to Excel",
                verbose_name="is exported",
            ),
        ),
        migrations.AddField(
            model_name="summervoucher",
            name="is_exported",
            field=models.BooleanField(
                default=False,
                help_text="Has been exported to Excel",
                verbose_name="is exported",
            ),
        ),
    ]
