# Generated by Django 3.2.4 on 2021-12-02 11:12

import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0011_add_is_exported"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouthApplication",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="last name"
                    ),
                ),
                (
                    "encrypted_social_security_number",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=11, verbose_name="social security number"
                    ),
                ),
                (
                    "social_security_number",
                    encrypted_fields.fields.SearchField(
                        blank=True,
                        db_index=True,
                        encrypted_field_name="encrypted_social_security_number",
                        hash_key="ee235e39ebc238035a6264c063dd829d4b6d2270604b57ee1f463e676ec44669",
                        max_length=66,
                        null=True,
                        validators=[
                            common.utils.validate_optional_finnish_social_security_number
                        ],
                    ),
                ),
                (
                    "school",
                    models.CharField(blank=True, max_length=256, verbose_name="school"),
                ),
                ("is_unlisted_school", models.BooleanField(blank=True)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="phone number"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fi", "suomi"), ("sv", "svenska"), ("en", "english")],
                        default="fi",
                        max_length=2,
                    ),
                ),
                (
                    "receipt_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="timestamp of receipt confirmation",
                    ),
                ),
            ],
            options={
                "verbose_name": "youth application",
                "verbose_name_plural": "youth applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="YouthSummerVoucher",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "summer_voucher_serial_number",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="summer voucher id"
                    ),
                ),
                (
                    "summer_voucher_exception_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("9th_grader", "9th grader"),
                            ("born_2004", "born 2004"),
                        ],
                        help_text="Special case of admitting the summer voucher.",
                        max_length=256,
                        verbose_name="summer voucher exception class",
                    ),
                ),
                (
                    "youth_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youth_summer_vouchers",
                        to="applications.youthapplication",
                        verbose_name="youth application",
                    ),
                ),
            ],
            options={
                "verbose_name": "youth summer voucher",
                "verbose_name_plural": "youth summer vouchers",
                "ordering": ["-youth_application__created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalYouthSummerVoucher",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="time modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "summer_voucher_serial_number",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="summer voucher id"
                    ),
                ),
                (
                    "summer_voucher_exception_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("9th_grader", "9th grader"),
                            ("born_2004", "born 2004"),
                        ],
                        help_text="Special case of admitting the summer voucher.",
                        max_length=256,
                        verbose_name="summer voucher exception class",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "youth_application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="applications.youthapplication",
                        verbose_name="youth application",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical youth summer voucher",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalYouthApplication",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="time modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="last name"
                    ),
                ),
                (
                    "encrypted_social_security_number",
                    encrypted_fields.fields.EncryptedCharField(
                        blank=True, max_length=11, verbose_name="social security number"
                    ),
                ),
                (
                    "social_security_number",
                    encrypted_fields.fields.SearchField(
                        blank=True,
                        db_index=True,
                        encrypted_field_name="encrypted_social_security_number",
                        hash_key="ee235e39ebc238035a6264c063dd829d4b6d2270604b57ee1f463e676ec44669",
                        max_length=66,
                        null=True,
                        validators=[
                            common.utils.validate_optional_finnish_social_security_number
                        ],
                    ),
                ),
                (
                    "school",
                    models.CharField(blank=True, max_length=256, verbose_name="school"),
                ),
                ("is_unlisted_school", models.BooleanField(blank=True)),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="phone number"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fi", "suomi"), ("sv", "svenska"), ("en", "english")],
                        default="fi",
                        max_length=2,
                    ),
                ),
                (
                    "receipt_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="timestamp of receipt confirmation",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical youth application",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
