# Generated by Django 3.2.4 on 2021-12-14 10:53

import applications.models
import common.utils
import shared.common.validators
from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_set_real_schools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalyouthapplication",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="historicalyouthapplication",
            name="encrypted_social_security_number",
            field=encrypted_fields.fields.EncryptedCharField(
                max_length=11, verbose_name="social security number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalyouthapplication",
            name="first_name",
            field=models.CharField(
                max_length=128,
                validators=[shared.common.validators.validate_name],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalyouthapplication",
            name="is_unlisted_school",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="historicalyouthapplication",
            name="last_name",
            field=models.CharField(
                max_length=128,
                validators=[shared.common.validators.validate_name],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalyouthapplication",
            name="phone_number",
            field=models.CharField(
                max_length=64,
                validators=[shared.common.validators.validate_phone_number],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalyouthapplication",
            name="school",
            field=models.CharField(
                max_length=256,
                validators=[applications.models.validate_name],
                verbose_name="school",
            ),
        ),
        migrations.AlterField(
            model_name="historicalyouthapplication",
            name="social_security_number",
            field=encrypted_fields.fields.SearchField(
                blank=True,
                db_index=True,
                encrypted_field_name="encrypted_social_security_number",
                hash_key="ee235e39ebc238035a6264c063dd829d4b6d2270604b57ee1f463e676ec44669",
                max_length=66,
                null=True,
                validators=[common.utils.validate_finnish_social_security_number],
            ),
        ),
        migrations.AlterField(
            model_name="youthapplication",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="youthapplication",
            name="encrypted_social_security_number",
            field=encrypted_fields.fields.EncryptedCharField(
                max_length=11, verbose_name="social security number"
            ),
        ),
        migrations.AlterField(
            model_name="youthapplication",
            name="first_name",
            field=models.CharField(
                max_length=128,
                validators=[shared.common.validators.validate_name],
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="youthapplication",
            name="is_unlisted_school",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="youthapplication",
            name="last_name",
            field=models.CharField(
                max_length=128,
                validators=[shared.common.validators.validate_name],
                verbose_name="last name",
            ),
        ),
        migrations.AlterField(
            model_name="youthapplication",
            name="phone_number",
            field=models.CharField(
                max_length=64,
                validators=[shared.common.validators.validate_phone_number],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="youthapplication",
            name="school",
            field=models.CharField(
                max_length=256,
                validators=[applications.models.validate_name],
                verbose_name="school",
            ),
        ),
        migrations.AlterField(
            model_name="youthapplication",
            name="social_security_number",
            field=encrypted_fields.fields.SearchField(
                blank=True,
                db_index=True,
                encrypted_field_name="encrypted_social_security_number",
                hash_key="ee235e39ebc238035a6264c063dd829d4b6d2270604b57ee1f463e676ec44669",
                max_length=66,
                null=True,
                validators=[common.utils.validate_finnish_social_security_number],
            ),
        ),
    ]
