# Generated by Django 3.2.4 on 2022-01-14 09:32

from django.db import migrations
import encrypted_fields.fields
import shared.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0020_rename_summer_voucher_to_employer_summer_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="youthapplication",
            name="encrypted_vtj_json",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                max_length=1048576,
                null=True,
                validators=[shared.common.validators.validate_optional_json],
                verbose_name="vtj json",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalYouthApplication",
        ),
    ]
