# Generated by Django 3.2.4 on 2022-01-24 11:35

from django.db import migrations, models
import shared.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0021_add_encrypted_vtj_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="youthapplication",
            name="postcode",
            field=models.CharField(
                default="00000",
                max_length=5,
                validators=[shared.common.validators.validate_postcode],
                verbose_name="postcode",
            ),
            preserve_default=False,
        ),
    ]
