# Generated by Django 3.2.4 on 2022-01-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0022_youthapplication_postcode"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="youthapplication",
            index=models.Index(
                fields=["created_at"], name="application_created_2399a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="youthapplication",
            index=models.Index(fields=["email"], name="application_email_7f3d4f_idx"),
        ),
        migrations.AddIndex(
            model_name="youthapplication",
            index=models.Index(
                fields=["receipt_confirmed_at"], name="application_receipt_7e5473_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="youthapplication",
            index=models.Index(
                fields=["social_security_number"], name="application_social__d43cda_idx"
            ),
        ),
    ]
