# Generated by Django 3.2.4 on 2022-02-28 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0024_youthapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="youthapplication",
            name="handled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="time handled"
            ),
        ),
        migrations.AddField(
            model_name="youthapplication",
            name="handler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="youth_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="handler",
            ),
        ),
    ]
