# Generated by Django 3.2.4 on 2022-03-01 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0025_youthapplication_handler_and_handled_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youthsummervoucher",
            options={
                "ordering": ["summer_voucher_serial_number"],
                "verbose_name": "youth summer voucher",
                "verbose_name_plural": "youth summer vouchers",
            },
        ),
        migrations.AlterField(
            model_name="historicalyouthsummervoucher",
            name="summer_voucher_serial_number",
            field=models.PositiveBigIntegerField(
                db_index=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="summer voucher id",
            ),
        ),
        migrations.AlterField(
            model_name="youthsummervoucher",
            name="summer_voucher_serial_number",
            field=models.PositiveBigIntegerField(
                unique=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="summer voucher id",
            ),
        ),
        migrations.AlterField(
            model_name="youthsummervoucher",
            name="youth_application",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="youth_summer_voucher",
                to="applications.youthapplication",
                verbose_name="youth application",
            ),
        ),
    ]
