# Generated by Django 3.2.4 on 2022-03-22 09:30

import applications.api.v1.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0026_youth_summer_voucher_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="youthapplication",
            name="additional_info_description",
            field=models.CharField(
                blank=True,
                default="",
                max_length=4096,
                verbose_name="additional info description",
            ),
        ),
        migrations.AddField(
            model_name="youthapplication",
            name="additional_info_provided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="time additional info was provided"
            ),
        ),
        migrations.AddField(
            model_name="youthapplication",
            name="additional_info_user_reasons",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[
                    applications.api.v1.validators.validate_additional_info_user_reasons
                ],
                verbose_name="additional info user reasons",
            ),
        ),
    ]
