# Generated by Django 4.2.14 on 2024-07-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0035_add_youth_application_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalemployerapplication",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical application",
                "verbose_name_plural": "historical applications",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalemployersummervoucher",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical summer voucher",
                "verbose_name_plural": "historical summer vouchers",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalyouthsummervoucher",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical youth summer voucher",
                "verbose_name_plural": "historical youth summer vouchers",
            },
        ),
        migrations.AlterField(
            model_name="historicalemployerapplication",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalemployersummervoucher",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalyouthsummervoucher",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
