from django.db import migrations, transaction

YEAR_2026_SCHOOL_LIST = [
    "Aleksis Kiven peruskoulu",
    "Alppilan lukio",
    "Ammattiopisto Luovi, Helsingin yksikkö",
    "Apollon yhteiskoulu",
    "Arabian peruskoulu",
    "Aurinkolahden peruskoulu",
    "Botby grundskola",
    "Brändö gymnasium",
    "Business College Helsinki",
    "Crusellin peruskoulu",
    "Elias-koulu",
    "Elias-koulun lukio",
    "Etu-Töölön lukio",
    "Grundskolan Norsen",
    "Gymnasiet Lärkan",
    "Haagan peruskoulu",
    "Helsingin Juutalainen yhteiskoulu",
    "Helsingin Konservatorio",
    "Helsingin Kristillinen koulu",
    "Helsingin Saksalainen koulu",
    "Helsingin Suomalainen Yhteiskoulu",
    "Helsingin Uusi Yhteiskoulu",
    "Helsingin kielilukio",
    "Helsingin kuvataidelukio",
    "Helsingin luonnontiedelukio",
    "Helsingin maalariammattikoulu",
    "Helsingin medialukio",
    "Helsingin normaalilyseo",
    "Helsingin ranskalais-suomalainen koulu",
    "Helsingin yhteislyseo",
    "Helsingin yliopiston Viikin normaalikoulu",
    "Herttoniemen yhteiskoulu",
    "Hiidenkiven peruskoulu",
    "Hoplaxskolan",
    "Itäkeskuksen peruskoulu",
    "Jätkäsaaren peruskoulu",
    "Kalasataman peruskoulu",
    "Kallion lukio",
    "Kankarepuiston peruskoulu",
    "Kannelmäen peruskoulu",
    "Karviaistien koulu",
    "Konepajan lukio, Pälkäneentien toimipaikka",
    "Konepajan lukio, Töysänkadun toimipaikka",
    "Kottby grundskola",
    "Kruununhaan yläasteen koulu",
    "Kruunuvuorenrannan peruskoulu",
    "Kulosaaren yhteiskoulu",
    "Käpylän peruskoulu",
    "Laajasalon peruskoulu",
    "Latokartanon peruskoulu",
    "Lauttasaaren yhteiskoulu",
    "Lauttasaaren yhteiskoulu, Kansainvälisen liiketoiminnan lukio",
    "Maatullin peruskoulu",
    "Malmin peruskoulu",
    "Maunulan yhteiskoulu ja Helsingin matematiikkalukio",
    "Meilahden yläasteen koulu",
    "Merilahden peruskoulu",
    "Munkkiniemen yhteiskoulu",
    "Myllypuron peruskoulu",
    "Mäkelänrinteen lukio",
    "Oulunkylän yhteiskoulu",
    "Pakilan peruskoulu",
    "Pasilan peruskoulu",
    "Perho Liiketalousopisto",
    "Pitäjänmäen peruskoulu",
    "Pohjois-Haagan yhteiskoulu",
    "Pohjoismainen yhtenäiskoulu",
    "Pop & Jazz Konservatorio",
    "Porolahden peruskoulu",
    "Puistolan peruskoulu",
    "Puistopolun peruskoulu",
    "Pukinmäenkaaren peruskoulu",
    "Ressun lukio",
    "Ressun peruskoulu",
    "SKY-Opisto",
    "Sakarinmäen peruskoulu",
    "Sibelius-lukio",
    "Solakallion koulu",
    "Sophie Mannerheimin koulu",
    "Stadin ammattiopisto",
    "Stadin ammattiopisto, Abraham Wetterin tien toimipaikka",
    "Stadin ammattiopisto, Hattulantien toimipaikka",
    "Stadin ammattiopisto, Ilkantien toimipaikka",
    "Stadin ammattiopisto, Kullervonkadun toimipaikka",
    "Stadin ammattiopisto, Meritalon toimipaikka",
    "Stadin ammattiopisto, Muotoilijankadun toimipaikka",
    "Stadin ammattiopisto, Myllypuron toimipaikka",
    "Stadin ammattiopisto, Nilsiänkadun toimipaikka",
    "Stadin ammattiopisto, Prinsessantien toimipaikka",
    "Stadin ammattiopisto, Roihupellon toimipaikka",
    "Stadin ammattiopisto, Savonkadun toimipaikka",
    "Stadin ammattiopisto, Teollisuuskadun toimipaikka",
    "Stadin ammattiopisto, Vilppulantien toimipaikka",
    "Stadin ammattiopisto, Vuokkiniemenkadun toimipaikka",
    "Steinergymnasiet (Rudolf Steinerskolan i Helsingfors)",
    "Suomalais-venäläinen koulu",
    "Suomalais-venäläisen koulun lukio",
    "Suomen Diakoniaopisto",
    "Suomen kansallisoopperan ja -baletin balettioppilaitos",
    "Suutarilan peruskoulu",
    "Taivallahden peruskoulu",
    "The English School High School",
    "The English School",
    "Toivolan koulu",
    "Torpparinmäen peruskoulu",
    "Tölö gymnasium",
    "Töölön yhteiskoulu",
    "Töölön yhteiskoulun lukio",
    "Vartiokylän yläasteen koulu",
    "Vesalan peruskoulu",
    "Vuoniityn peruskoulu",
    "Vuosaaren lukio",
    "Zacharias Topeliusskolan",
]


def set_year_2026_schools(apps, schema_editor):
    school_model = apps.get_model("applications", "School")
    with transaction.atomic():
        school_model.objects.all().delete()
        for school in YEAR_2026_SCHOOL_LIST:
            school_model.objects.create(name=school)


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0036_alter_historicalemployerapplication_options_and_more"),
    ]

    operations = [
        migrations.RunPython(set_year_2026_schools, migrations.RunPython.noop),
    ]
