# Generated by Django 5.1.15 on 2026-01-08 12:51

import django.contrib.postgres.fields
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0037_set_year_2026_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummerVoucherConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2020)], verbose_name='year')),
                ('voucher_value_in_euros', models.PositiveIntegerField(verbose_name='voucher value in euros')),
                ('min_work_compensation_in_euros', models.PositiveIntegerField(verbose_name='minimum work compensation in euros')),
                ('min_work_hours', models.PositiveIntegerField(verbose_name='minimum work hours')),
                ('target_group', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('primary_target_group', '9. luokkalainen'), ('secondary_target_group', 'Toisen asteen ensimmäisen vuoden opiskelija')], max_length=256), size=None, verbose_name='target group')),
            ],
            options={
                'verbose_name': 'summer voucher configuration',
                'verbose_name_plural': 'summer voucher configurations',
                'ordering': ['-year'],
            },
        ),
        migrations.AlterField(
            model_name='employersummervoucher',
            name='target_group',
            field=models.CharField(blank=True, choices=[('primary_target_group', '9. luokkalainen'), ('secondary_target_group', 'Toisen asteen ensimmäisen vuoden opiskelija')], help_text="Summer voucher's target group type", max_length=256, verbose_name='summer voucher target group'),
        ),
        migrations.AlterField(
            model_name='historicalemployersummervoucher',
            name='target_group',
            field=models.CharField(blank=True, choices=[('primary_target_group', '9. luokkalainen'), ('secondary_target_group', 'Toisen asteen ensimmäisen vuoden opiskelija')], help_text="Summer voucher's target group type", max_length=256, verbose_name='summer voucher target group'),
        ),
        migrations.AlterField(
            model_name='historicalyouthsummervoucher',
            name='target_group',
            field=models.CharField(blank=True, choices=[('primary_target_group', '9. luokkalainen'), ('secondary_target_group', 'Toisen asteen ensimmäisen vuoden opiskelija')], help_text="Summer voucher's target group type", max_length=256, verbose_name='summer voucher target group'),
        ),
        migrations.AlterField(
            model_name='youthsummervoucher',
            name='target_group',
            field=models.CharField(blank=True, choices=[('primary_target_group', '9. luokkalainen'), ('secondary_target_group', 'Toisen asteen ensimmäisen vuoden opiskelija')], help_text="Summer voucher's target group type", max_length=256, verbose_name='summer voucher target group'),
        ),
    ]
