# Generated by Django 5.1.15 on 2026-01-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0038_summervoucherconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='alias',
            field=models.CharField(blank=True, help_text='Alias or secondary name for the school. Used internally e.g. in reports.', max_length=256, null=True),
        ),
    ]
