# Generated by Django 5.1.15 on 2026-01-09 16:22

import uuid

from django.db import migrations, models

import applications.validators


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0038_summervoucherconfiguration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("activation", "Activation"),
                            (
                                "additional_info_request",
                                "Additional information request",
                            ),
                            ("processing", "Processing"),
                            ("youth_summer_voucher", "Youth summer voucher"),
                        ],
                        max_length=64,
                        verbose_name="template type",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fi", "suomi"), ("sv", "svenska"), ("en", "english")],
                        max_length=2,
                        verbose_name="language",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=255,
                        validators=[applications.validators.validate_template_syntax],
                        verbose_name="subject",
                    ),
                ),
                (
                    "html_body",
                    models.TextField(
                        validators=[applications.validators.validate_template_syntax],
                        verbose_name="HTML body",
                    ),
                ),
                (
                    "text_body",
                    models.TextField(
                        blank=True,
                        help_text="Text body will be auto-generated from HTML body.",
                        validators=[applications.validators.validate_template_syntax],
                        verbose_name="text body",
                    ),
                ),
            ],
            options={
                "verbose_name": "email template",
                "verbose_name_plural": "email templates",
                "ordering": ["type", "language"],
                "unique_together": {("type", "language")},
            },
        ),
    ]
