# Generated by Django 5.1.15 on 2026-02-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0044_remove_employersummervoucher_target_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employersummervoucher",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sports_and_leisure", "Sports and leisure"),
                    ("maintenance_and_construction", "Maintenance and construction"),
                    ("restaurant_and_cafe", "Restaurant and cafe sector"),
                    ("retail", "Retail sector"),
                    ("office_and_media", "Office and media"),
                    ("gardening_and_agriculture", "Gardening and agricultural work"),
                    ("service", "Service sector"),
                    ("other", "Other"),
                ],
                max_length=64,
                verbose_name="job type",
            ),
        ),
        migrations.AddField(
            model_name="historicalemployersummervoucher",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sports_and_leisure", "Sports and leisure"),
                    ("maintenance_and_construction", "Maintenance and construction"),
                    ("restaurant_and_cafe", "Restaurant and cafe sector"),
                    ("retail", "Retail sector"),
                    ("office_and_media", "Office and media"),
                    ("gardening_and_agriculture", "Gardening and agricultural work"),
                    ("service", "Service sector"),
                    ("other", "Other"),
                ],
                max_length=64,
                verbose_name="job type",
            ),
        ),
    ]
