# Generated by Django 5.1.15 on 2026-02-04 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0045_employersummervoucher_job_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employerapplication",
            options={
                "ordering": ["-created_at", "id"],
                "verbose_name": "employer application",
                "verbose_name_plural": "employer applications",
            },
        ),
    ]
