# Generated by Django 5.1.15 on 2026-02-09 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0046_make_employerapplication_ordering_consistent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalyouthsummervoucher",
            name="target_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hki_15", "8. luokkalainen"),
                    ("primary_target_group", "9. luokkalainen"),
                    (
                        "secondary_target_group",
                        "Toisen asteen ensimmäisen vuoden opiskelija",
                    ),
                    ("hki_18", "Toisen asteen toisen vuoden opiskelija"),
                ],
                help_text="Summer voucher's target group type",
                max_length=256,
                verbose_name="summer voucher target group",
            ),
        ),
        migrations.AlterField(
            model_name="summervoucherconfiguration",
            name="target_group",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("hki_15", "8. luokkalainen"),
                        ("primary_target_group", "9. luokkalainen"),
                        (
                            "secondary_target_group",
                            "Toisen asteen ensimmäisen vuoden opiskelija",
                        ),
                        ("hki_18", "Toisen asteen toisen vuoden opiskelija"),
                    ],
                    max_length=256,
                ),
                size=None,
                verbose_name="target group",
            ),
        ),
        migrations.AlterField(
            model_name="youthsummervoucher",
            name="target_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hki_15", "8. luokkalainen"),
                    ("primary_target_group", "9. luokkalainen"),
                    (
                        "secondary_target_group",
                        "Toisen asteen ensimmäisen vuoden opiskelija",
                    ),
                    ("hki_18", "Toisen asteen toisen vuoden opiskelija"),
                ],
                help_text="Summer voucher's target group type",
                max_length=256,
                verbose_name="summer voucher target group",
            ),
        ),
    ]
