# Generated by Django 5.1.15 on 2026-02-09 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "applications",
            "0047_alter_historicalyouthsummervoucher_target_group_and_more",
        ),
        ("companies", "0011_company_add_name_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employerapplication",
            index=models.Index(
                fields=["created_at"], name="employer_app_created_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employerapplication",
            index=models.Index(
                fields=["modified_at"], name="employer_app_modified_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employerapplication",
            index=models.Index(fields=["status"], name="employer_app_status_idx"),
        ),
    ]
