# Generated by Django 5.1.15 on 2026-02-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0048_employerapplication_add_timestamp_and_status_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employersummervoucher',
            name='employee_home_city',
        ),
        migrations.RemoveField(
            model_name='employersummervoucher',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='employersummervoucher',
            name='employee_postcode',
        ),
        migrations.RemoveField(
            model_name='employersummervoucher',
            name='employee_school',
        ),
        migrations.RemoveField(
            model_name='employersummervoucher',
            name='employee_ssn',
        ),
        migrations.RemoveField(
            model_name='historicalemployersummervoucher',
            name='employee_home_city',
        ),
        migrations.RemoveField(
            model_name='historicalemployersummervoucher',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='historicalemployersummervoucher',
            name='employee_postcode',
        ),
        migrations.RemoveField(
            model_name='historicalemployersummervoucher',
            name='employee_school',
        ),
        migrations.RemoveField(
            model_name='historicalemployersummervoucher',
            name='employee_ssn',
        ),
    ]
