# Generated by Django 5.2.12 on 2026-03-05 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "applications",
            "0049_remove_employersummervoucher_employee_home_city_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalemployersummervoucher",
            name="application",
        ),
        migrations.RemoveField(
            model_name="historicalemployersummervoucher",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalemployersummervoucher",
            name="youth_summer_voucher",
        ),
        migrations.RemoveField(
            model_name="historicalyouthsummervoucher",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalyouthsummervoucher",
            name="youth_application",
        ),
        migrations.DeleteModel(
            name="HistoricalEmployerApplication",
        ),
        migrations.DeleteModel(
            name="HistoricalEmployerSummerVoucher",
        ),
        migrations.DeleteModel(
            name="HistoricalYouthSummerVoucher",
        ),
    ]
