# Generated by Django 5.2.12 on 2026-03-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0049_remove_employersummervoucher_employee_home_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youthapplication',
            name='target_group',
            field=models.CharField(blank=True, choices=[('hki_15', '8. luokkalainen'), ('primary_target_group', '9. luokkalainen'), ('secondary_target_group', 'Toisen asteen ensimmäisen vuoden opiskelija'), ('hki_18', 'Toisen asteen toisen vuoden opiskelija')], max_length=256, verbose_name='target group'),
        ),
    ]
