# Generated by Django 5.2.12 on 2026-03-25 10:38

from django.db import migrations

BATCH_SIZE = 1000


def populate_target_group(apps, _schema_editor):
    """
    Forward migration: copies the `target_group` field from each
    `YouthSummerVoucher` to its associated `YouthApplication`.

    Background: Previously, `target_group` was stored only on `YouthSummerVoucher`.
    This migration populates the new `target_group` field on `YouthApplication`
    (added in migration 0050) from the existing voucher data, ensuring that
    all historical applications retain their target group assignment.

    Values are copied as raw strings without validation against the current set
    of target groups. This means legacy/deprecated identifiers (e.g., old names
    that have since been renamed or removed) are preserved faithfully in the
    database. Only vouchers with a non-empty `target_group` are processed.
    Updates are batched to avoid excessive memory usage.
    """
    YouthApplication = apps.get_model("applications", "YouthApplication")
    YouthSummerVoucher = apps.get_model("applications", "YouthSummerVoucher")

    vouchers = YouthSummerVoucher.objects.exclude(target_group="").select_related(
        "youth_application"
    )

    applications_to_update = []
    for voucher in vouchers.iterator(chunk_size=BATCH_SIZE):
        application = voucher.youth_application
        if application.target_group != voucher.target_group:
            application.target_group = voucher.target_group
            applications_to_update.append(application)

        if len(applications_to_update) >= BATCH_SIZE:
            YouthApplication.objects.bulk_update(
                applications_to_update, ["target_group"]
            )
            applications_to_update = []

    if applications_to_update:
        YouthApplication.objects.bulk_update(applications_to_update, ["target_group"])


def reverse_populate_target_group(apps, _schema_editor):
    """
    Reverse migration: copies the `target_group` field from each
    `YouthApplication` back to its associated `YouthSummerVoucher`.

    This reverses the forward migration by restoring the `target_group`
    on `YouthSummerVoucher`, so that rolling back migration 0050
    (which removes the field from `YouthApplication`) does not result
    in data loss. Only vouchers linked to an application with a non-empty
    `target_group` are updated.
    Updates are batched to avoid excessive memory usage.
    """
    YouthSummerVoucher = apps.get_model("applications", "YouthSummerVoucher")

    vouchers = YouthSummerVoucher.objects.select_related("youth_application")

    vouchers_to_update = []
    for voucher in vouchers.iterator(chunk_size=BATCH_SIZE):
        application = voucher.youth_application
        if application and application.target_group:
            voucher.target_group = application.target_group
            vouchers_to_update.append(voucher)

        if len(vouchers_to_update) >= BATCH_SIZE:
            YouthSummerVoucher.objects.bulk_update(vouchers_to_update, ["target_group"])
            vouchers_to_update = []

    if vouchers_to_update:
        YouthSummerVoucher.objects.bulk_update(vouchers_to_update, ["target_group"])


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0050_add_target_group_to_youth_application"),
    ]

    operations = [
        migrations.RunPython(populate_target_group, reverse_populate_target_group),
    ]
