# Generated by Django 5.2.13 on 2026-04-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0054_employerapplication_submitted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerapplication",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text="Enter the whole company postal address including street address, postcode and city.",
                max_length=256,
                verbose_name="company postal address",
            ),
        ),
    ]
