# Generated by Django 5.2.13 on 2026-04-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0055_alter_employerapplication_street_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="youthapplication",
            name="is_vtj_data_restricted",
            field=models.BooleanField(
                default=False,
                help_text="The Population Information System (VTJ) has restricted data disclosure (a non-disclosure of personal data / turvakielto). This prevents automatic retrieval of municipality and address data, requiring manual application processing.",
                verbose_name="is vtj data restricted",
            ),
        ),
    ]
