# Generated by Django 5.2.13 on 2026-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0057_backfill_vtj_restriction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerapplication",
            name="bank_address",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="bank address"
            ),
        ),
        migrations.AddField(
            model_name="employerapplication",
            name="bank_name",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="bank name"
            ),
        ),
        migrations.AddField(
            model_name="employerapplication",
            name="bank_swift_bic_code",
            field=models.CharField(
                blank=True, max_length=11, verbose_name="bank SWIFT/BIC code"
            ),
        ),
        migrations.AddField(
            model_name="employerapplication",
            name="payee_address",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="payee address"
            ),
        ),
        migrations.AddField(
            model_name="employerapplication",
            name="payee_name",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="payee name"
            ),
        ),
    ]
