# Generated by Django 5.2.15 on 2026-06-16 12:58

import encrypted_fields.fields
from django.db import migrations

import applications.models
import common.utils


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0059_remove_sequence_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youthapplication",
            name="social_security_number",
            field=encrypted_fields.fields.SearchField(
                blank=True,
                db_index=True,
                encrypted_field_name="encrypted_social_security_number",
                hash_key=applications.models.get_social_security_number_hash_key,
                max_length=66,
                null=True,
                validators=[
                    common.utils.validate_optional_finnish_social_security_number
                ],
            ),
        ),
    ]
