# Generated by Django 5.2.15 on 2026-07-16 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0060_alter_youthapplication_social_security_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineActivityLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "application_type",
                    models.CharField(max_length=64, verbose_name="application type"),
                ),
                ("application_id", models.UUIDField(verbose_name="application id")),
                (
                    "from_status",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="from status"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(max_length=64, verbose_name="to status"),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        help_text='Non-PII actor name; "Deleted User" for removed accounts',
                        max_length=256,
                        verbose_name="actor name snapshot",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "timeline activity log",
                "verbose_name_plural": "timeline activity logs",
                "db_table": "applications_timelineactivitylog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application_type", "application_id", "created_at"],
                        name="tl_activity_app_type_id_ts_idx",
                    )
                ],
            },
        ),
    ]
