# Generated by Django 5.2.16 on 2026-08-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0061_timelineactivitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    (
                        "additional_information_requested",
                        "Additional information requested",
                    ),
                    (
                        "additional_information_provided",
                        "Additional information provided",
                    ),
                    ("application_handling", "Application handling"),
                    ("payment_review", "Payment review"),
                    ("accepted_for_payment", "Accepted for payment"),
                    ("sent_for_payment", "Sent for payment"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=64,
                verbose_name="status",
            ),
        ),
    ]
