# Generated by Django 5.2.15 on 2026-09-01 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0063_alter_employerapplication_status"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timelineactivitylog",
            old_name="from_status",
            new_name="old_value",
        ),
        migrations.RenameField(
            model_name="timelineactivitylog",
            old_name="to_status",
            new_name="new_value",
        ),
        migrations.AddField(
            model_name="timelineactivitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("application_status_change", "Application status change"),
                    ("attachment_added", "Attachment added"),
                    ("attachment_deleted", "Attachment deleted"),
                ],
                default="application_status_change",
                max_length=64,
                verbose_name="action type",
            ),
        ),
        migrations.AlterField(
            model_name="timelineactivitylog",
            name="new_value",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="new value"
            ),
        ),
        migrations.AlterField(
            model_name="timelineactivitylog",
            name="old_value",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="old value"
            ),
        ),
        migrations.AddField(
            model_name="timelineactivitylog",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="target content type",
            ),
        ),
        migrations.AddField(
            model_name="timelineactivitylog",
            name="target_object_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="target object id"
            ),
        ),
    ]
