# Generated by Django 5.2.15 on 2026-09-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0064_refactor_timeline_activity_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="employersummervoucher",
            name="invoiced_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="timestamp when sent to invoicing"
            ),
        ),
        migrations.AddField(
            model_name="employersummervoucher",
            name="talpa_request_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="external request ID",
            ),
        ),
        migrations.AlterField(
            model_name="employersummervoucher",
            name="is_exported",
            field=models.BooleanField(
                default=False,
                help_text="Has been exported to Excel or JSON",
                verbose_name="is exported",
            ),
        ),
    ]
