# Generated by Django 5.2.15 on 2026-09-10 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0066_attachment_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "ordering": ["-created_at", "pk"],
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
            },
        ),
        migrations.AddField(
            model_name="attachment",
            name="youth_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="applications.youthapplication",
                verbose_name="youth application",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("employment_contract", "employment contract"),
                    ("payslip", "payslip"),
                    ("unclassified", "unclassified"),
                ],
                max_length=64,
                verbose_name="attachment type in business rules",
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="summer_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="applications.employersummervoucher",
                verbose_name="employer summer voucher",
            ),
        ),
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("summer_voucher__isnull", False),
                        ("youth_application__isnull", True),
                    ),
                    models.Q(
                        ("summer_voucher__isnull", True),
                        ("youth_application__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="attachment_must_belong_to_exactly_one_application_type",
            ),
        ),
    ]
