# Generated by Django 5.2.15 on 2026-09-21 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0068_alter_employerapplication_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employerapplication",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_employer_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignee",
            ),
        ),
        migrations.AddField(
            model_name="employerapplication",
            name="handler",
            field=models.ForeignKey(
                blank=True,
                help_text="The handler who made the final accept/reject decision.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_employer_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="handler",
            ),
        ),
        migrations.AddField(
            model_name="youthapplication",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_youth_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assignee",
            ),
        ),
        migrations.AlterField(
            model_name="timelineactivitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("application_status_change", "Application status change"),
                    ("assignee_change", "Assignee change"),
                    ("attachment_added", "Attachment added"),
                    ("attachment_deleted", "Attachment deleted"),
                ],
                default="application_status_change",
                max_length=64,
                verbose_name="action type",
            ),
        ),
        migrations.AlterField(
            model_name="youthapplication",
            name="handler",
            field=models.ForeignKey(
                blank=True,
                help_text="The handler who made the final accept/reject decision.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_youth_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="handler",
            ),
        ),
        migrations.AlterField(
            model_name="youthapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("awaiting_manual_processing", "Awaiting manual processing"),
                    (
                        "additional_information_requested",
                        "Additional information requested",
                    ),
                    (
                        "additional_information_provided",
                        "Additional information provided",
                    ),
                    ("application_handling", "Application handling"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="submitted",
                max_length=64,
                verbose_name="status",
            ),
        ),
    ]
