# Generated by Django 5.2.16 on 2026-09-25 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0069_employerapplication_assignee_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employerapplication",
            name="accepted_for_payment_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="timestamp when last accepted for payment by approver",
            ),
        ),
        migrations.AddField(
            model_name="employerapplication",
            name="additional_info_provided_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="timestamp when additional info was last provided by employer",
            ),
        ),
        migrations.AddField(
            model_name="employerapplication",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who accepted employer application for payment i.e. approved it",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_employer_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approver",
            ),
        ),
        migrations.AddField(
            model_name="employerapplication",
            name="handled_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="timestamp when last handled by handler or approver",
            ),
        ),
    ]
