# Generated by Django 5.2.16 on 2026-10-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0070_employerapplication_accepted_for_payment_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("activation", "Activation"),
                    ("additional_info_request", "Additional information request"),
                    ("processing", "Processing"),
                    ("youth_summer_voucher", "Youth summer voucher"),
                    ("external_message", "External message"),
                    ("youth_external_message", "Youth external message"),
                    ("employer_external_message", "Employer external message"),
                ],
                max_length=64,
                verbose_name="template type",
            ),
        ),
    ]
