import React from 'react';

import { APPLICATION_FIELDS, DE_MINIMIS_AID_FIELDS } from '../constants';

export type DynamicFormStepComponentProps = {
  actions?: React.ReactElement;
};

export type DeMinimisAidGrant = {
  [DE_MINIMIS_AID_FIELDS.GRANTER]: string;
  [DE_MINIMIS_AID_FIELDS.AMOUNT]: number;
  [DE_MINIMIS_AID_FIELDS.ISSUE_DATE]: string;
};

export type Application = {
  [APPLICATION_FIELDS.HAS_COMPANY_OTHER_ADDRESS]?: boolean;
  [APPLICATION_FIELDS.COMPANY_OTHER_ADDRESS_STREET]?: string;
  [APPLICATION_FIELDS.COMPANY_OTHER_ADDRESS_ZIP]?: string;
  [APPLICATION_FIELDS.COMPANY_OTHER_ADDRESS_DISTRICT]?: string;
  [APPLICATION_FIELDS.COMPANY_IBAN]?: string;
  [APPLICATION_FIELDS.CONTACT_PERSON_FIRST_NAME]?: string;
  [APPLICATION_FIELDS.CONTACT_PERSON_LAST_NAME]?: string;
  [APPLICATION_FIELDS.CONTACT_PERSON_PHONE]?: string;
  [APPLICATION_FIELDS.CONTACT_PERSON_EMAIL]?: string;
  [APPLICATION_FIELDS.DE_MINIMIS_AIDS_GRANTED]?: boolean;
  deMinimisAidGrants?: DeMinimisAidGrant[];
  [APPLICATION_FIELDS.COLLECTIVE_BARGAINING_ONGOING]?: string;
  [APPLICATION_FIELDS.COLLECTIVE_BARGAINING_INFO]?: string;
};
