# Generated by Django 3.2 on 2021-05-05 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            (
                                "additional_information_requested",
                                "Additional information requested",
                            ),
                            (
                                "additional_information_provided",
                                "Additional information provided",
                            ),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("deleted_by_customer", "Deleted by customer"),
                        ],
                        max_length=64,
                        verbose_name="status",
                    ),
                ),
                (
                    "invoicer_name",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="invoicer name"
                    ),
                ),
                (
                    "invoicer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="invoicer email"
                    ),
                ),
                (
                    "invoicer_phone_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="invoicer phone number"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SummerVoucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "summer_voucher_id",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="summer voucher id"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="contact name"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="contact email"
                    ),
                ),
                (
                    "work_postcode",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="work postcode"
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="employee name"
                    ),
                ),
                (
                    "employee_school",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="employee school"
                    ),
                ),
                (
                    "employee_ssn",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            blank=True,
                            max_length=32,
                            verbose_name="employee social security number",
                        )
                    ),
                ),
                (
                    "employee_phone_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="employee phone number"
                    ),
                ),
                (
                    "is_unnumbered_summer_voucher",
                    models.BooleanField(
                        default=False, verbose_name="is unnumbered summer voucher"
                    ),
                ),
                (
                    "unnumbered_summer_voucher_reason",
                    models.TextField(
                        default="", verbose_name="unnumbered summer voucher reason"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summer_vouchers",
                        to="applications.application",
                        verbose_name="application",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalSummerVoucher",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "summer_voucher_id",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="summer voucher id"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="contact name"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="contact email"
                    ),
                ),
                (
                    "work_postcode",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="work postcode"
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="employee name"
                    ),
                ),
                (
                    "employee_school",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="employee school"
                    ),
                ),
                (
                    "employee_ssn",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            blank=True,
                            max_length=32,
                            verbose_name="employee social security number",
                        )
                    ),
                ),
                (
                    "employee_phone_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="employee phone number"
                    ),
                ),
                (
                    "is_unnumbered_summer_voucher",
                    models.BooleanField(
                        default=False, verbose_name="is unnumbered summer voucher"
                    ),
                ),
                (
                    "unnumbered_summer_voucher_reason",
                    models.TextField(
                        default="", verbose_name="unnumbered summer voucher reason"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="applications.application",
                        verbose_name="application",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical summer voucher",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            (
                                "additional_information_requested",
                                "Additional information requested",
                            ),
                            (
                                "additional_information_provided",
                                "Additional information provided",
                            ),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("deleted_by_customer", "Deleted by customer"),
                        ],
                        max_length=64,
                        verbose_name="status",
                    ),
                ),
                (
                    "invoicer_name",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="invoicer name"
                    ),
                ),
                (
                    "invoicer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="invoicer email"
                    ),
                ),
                (
                    "invoicer_phone_number",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="invoicer phone number"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical application",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
