# Generated by Django 3.2.4 on 2021-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DescriptionRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
        migrations.CreateModel(
            name="PaySubsidyMonthlyRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
        migrations.CreateModel(
            name="SalaryBenefitMonthlyRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
        migrations.CreateModel(
            name="SalaryBenefitSubTotalRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
        migrations.CreateModel(
            name="SalaryBenefitSumSubTotalsRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
        migrations.CreateModel(
            name="SalaryBenefitTotalRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
        migrations.CreateModel(
            name="SalaryCostsRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
        migrations.CreateModel(
            name="StateAidMaxMonthlyRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
        migrations.AddField(
            model_name="historicalpaysubsidy",
            name="pay_subsidy_percent",
            field=models.IntegerField(
                blank=True,
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                null=True,
                verbose_name="Pay subsidy percent",
            ),
        ),
        migrations.AddField(
            model_name="historicalpaysubsidy",
            name="work_time_percent",
            field=models.IntegerField(
                blank=True, default=100, null=True, verbose_name="Work time percent"
            ),
        ),
        migrations.AddField(
            model_name="paysubsidy",
            name="pay_subsidy_percent",
            field=models.IntegerField(
                blank=True,
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                null=True,
                verbose_name="Pay subsidy percent",
            ),
        ),
        migrations.AddField(
            model_name="paysubsidy",
            name="work_time_percent",
            field=models.IntegerField(
                blank=True, default=100, null=True, verbose_name="Work time percent"
            ),
        ),
        migrations.AlterField(
            model_name="calculationrow",
            name="row_type",
            field=models.CharField(
                choices=[
                    ("description", "Description row, amount ignored"),
                    ("salary_costs", "Salary costs"),
                    ("state_aid_max_monthly_eur", "State aid maximum %"),
                    ("pay_subsidy_monthly_eur", "Pay subsidy/month"),
                    ("helsinki_benefit_monthly_eur", "Helsinki benefit amount monthly"),
                    (
                        "helsinki_benefit_sub_total_eur",
                        "Helsinki benefit amount for a date range",
                    ),
                    ("helsinki_benefit_total_eur", "Helsinki benefit total amount"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcalculationrow",
            name="row_type",
            field=models.CharField(
                choices=[
                    ("description", "Description row, amount ignored"),
                    ("salary_costs", "Salary costs"),
                    ("state_aid_max_monthly_eur", "State aid maximum %"),
                    ("pay_subsidy_monthly_eur", "Pay subsidy/month"),
                    ("helsinki_benefit_monthly_eur", "Helsinki benefit amount monthly"),
                    (
                        "helsinki_benefit_sub_total_eur",
                        "Helsinki benefit amount for a date range",
                    ),
                    ("helsinki_benefit_total_eur", "Helsinki benefit total amount"),
                ],
                max_length=64,
            ),
        ),
    ]
