# Generated by Django 3.2.4 on 2021-10-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_simple_benefit_calculation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paysubsidy",
            options={
                "ordering": ["application__created_at", "ordering"],
                "verbose_name": "pay subsidy",
                "verbose_name_plural": "pay subsidies",
            },
        ),
        migrations.RemoveField(
            model_name="historicalpaysubsidy",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="paysubsidy",
            name="amount",
        ),
        migrations.AddField(
            model_name="calculation",
            name="granted_as_de_minimis_aid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calculation",
            name="target_group_check",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcalculation",
            name="granted_as_de_minimis_aid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcalculation",
            name="target_group_check",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalpaysubsidy",
            name="disability_or_illness",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalpaysubsidy",
            name="ordering",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paysubsidy",
            name="disability_or_illness",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paysubsidy",
            name="ordering",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="calculation",
            name="override_benefit_amount_comment",
            field=models.CharField(
                blank=True,
                max_length=256,
                verbose_name="reason for overriding the calculated benefit amount",
            ),
        ),
        migrations.AlterField(
            model_name="calculation",
            name="state_aid_max_percentage",
            field=models.IntegerField(
                choices=[(50, "50%"), (100, "100%")],
                default=50,
                verbose_name="State aid maximum %",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcalculation",
            name="override_benefit_amount_comment",
            field=models.CharField(
                blank=True,
                max_length=256,
                verbose_name="reason for overriding the calculated benefit amount",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcalculation",
            name="state_aid_max_percentage",
            field=models.IntegerField(
                choices=[(50, "50%"), (100, "100%")],
                default=50,
                verbose_name="State aid maximum %",
            ),
        ),
    ]
