# Generated by Django 3.2.4 on 2021-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_add_handler"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateRangeDescriptionRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
        migrations.AlterField(
            model_name="historicalpaysubsidy",
            name="pay_subsidy_percent",
            field=models.IntegerField(
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                default=50,
                verbose_name="Pay subsidy percent",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paysubsidy",
            name="pay_subsidy_percent",
            field=models.IntegerField(
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                default=50,
                verbose_name="Pay subsidy percent",
            ),
            preserve_default=False,
        ),
    ]
