# Generated by Django 3.2.4 on 2021-11-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0005_pay_subsidy_percent_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeBenefitMonthlyRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
        migrations.CreateModel(
            name="EmployeeBenefitTotalRow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculator.calculationrow",),
        ),
    ]
