# Generated by Django 3.2.4 on 2021-12-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0007_apprenticeship_calculation"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationrow",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AddField(
            model_name="calculationrow",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AddField(
            model_name="historicalcalculationrow",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AddField(
            model_name="historicalcalculationrow",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
    ]
