# Generated by Django 3.2.4 on 2022-02-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0008_add_start_end_time_to_calc_row"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpaysubsidy",
            name="work_time_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                max_digits=5,
                null=True,
                verbose_name="Work time percent",
            ),
        ),
        migrations.AlterField(
            model_name="paysubsidy",
            name="work_time_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=100,
                max_digits=5,
                null=True,
                verbose_name="Work time percent",
            ),
        ),
    ]
