# Generated by Django 3.2.4 on 2023-01-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_make_calculation_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='target_group_comment',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='calculation',
            name='target_group_decision',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcalculation',
            name='target_group_comment',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalcalculation',
            name='target_group_decision',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
