# Generated by Django 3.2.23 on 2024-04-02 07:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0015_desc_type_for_old_calc_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaysubsidy',
            name='work_time_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('65'), max_digits=5, null=True, verbose_name='Work time percent'),
        ),
        migrations.AlterField(
            model_name='paysubsidy',
            name='work_time_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('65'), max_digits=5, null=True, verbose_name='Work time percent'),
        ),
    ]
