# Generated by Django 4.2.11 on 2024-10-23 15:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0016_change_pay_subsidy_work_time_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instalment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instalment_number", models.IntegerField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="row amount",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due date"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("waiting", "Waiting"),
                            ("accepted", "Accepted"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("error_in_talpa", "Error in TALPA"),
                            ("completed", "Completed"),
                        ],
                        default="waiting",
                        max_length=64,
                        verbose_name="status",
                    ),
                ),
                (
                    "calculation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instalments",
                        to="calculator.calculation",
                        verbose_name="calculation",
                    ),
                ),
            ],
            options={
                "verbose_name": "instalment",
                "verbose_name_plural": "instalments",
                "db_table": "bf_calculator_instalment",
                "ordering": ("created_at",),
            },
        ),
    ]
