name: yjdh-kesaseteli
services:
  postgres:
    build:
      context: ../backend
      dockerfile: ./docker/finnish_postgres_17.Dockerfile
    restart: on-failure
    environment:
      POSTGRES_USER: kesaseteli
      POSTGRES_PASSWORD: kesaseteli
      POSTGRES_DB: kesaseteli
      LC_COLLATE: 'fi_FI.UTF-8'
      LC_CTYPE: 'fi_FI.UTF-8'
    ports:
      - 127.0.0.1:5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: kesaseteli-db

  backend:
    build:
      context: ../backend
      dockerfile: ./docker/kesaseteli.Dockerfile
    env_file:
      - ../.env.kesaseteli-backend
    environment:
      DATABASE_URL: postgres://kesaseteli:kesaseteli@kesaseteli-db/kesaseteli
      DATABASE_HOST: kesaseteli-db.helsinki
    depends_on:
      - postgres
    container_name: kesaseteli-backend

volumes:
  pgdata:
    driver: local

networks:
  default:
    name: helsinki
