# Generated by Django 3.2 on 2021-05-17 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OIDCProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id_token",
                    models.CharField(
                        blank=True, max_length=2048, verbose_name="id token"
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True, max_length=2048, verbose_name="access token"
                    ),
                ),
                (
                    "access_token_expires",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="access token expires"
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(
                        blank=True, max_length=2048, verbose_name="refresh token"
                    ),
                ),
                (
                    "refresh_token_expires",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="refresh token expires"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
