# Generated by Django 3.2.4 on 2021-11-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bf_messages", "0002_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "verbose_name": "message",
                "verbose_name_plural": "messages",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="seen_by_applicant",
            field=models.BooleanField(default=False, verbose_name="read by applicant"),
        ),
        migrations.AddField(
            model_name="message",
            name="seen_by_handler",
            field=models.BooleanField(default=False, verbose_name="read by applicant"),
        ),
    ]
