# Generated by Django 3.2.4 on 2021-09-15 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0019_searchable_social_security_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantConsent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text_fi",
                    models.CharField(
                        max_length=256,
                        verbose_name="finnish text for the consent checkbox",
                    ),
                ),
                (
                    "text_en",
                    models.CharField(
                        max_length=256,
                        verbose_name="english text for the consent checkbox",
                    ),
                ),
                (
                    "text_sv",
                    models.CharField(
                        max_length=256,
                        verbose_name="swedish text for the consent checkbox",
                    ),
                ),
            ],
            options={
                "verbose_name": "application consent",
                "verbose_name_plural": "application consents",
                "db_table": "bf_applicationconsents",
            },
        ),
        migrations.CreateModel(
            name="Terms",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "terms_type",
                    models.CharField(
                        choices=[
                            ("terms_of_service", "Terms of service - shown at login"),
                            (
                                "applicant_terms",
                                "Terms of application - show at application submit",
                            ),
                        ],
                        default="applicant_terms",
                        max_length=64,
                        verbose_name="type of terms",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="first day these terms are in effect",
                    ),
                ),
                (
                    "terms_pdf_fi",
                    models.FileField(
                        upload_to="", verbose_name="finnish terms (pdf file)"
                    ),
                ),
                (
                    "terms_pdf_en",
                    models.FileField(
                        upload_to="", verbose_name="english terms (pdf file)"
                    ),
                ),
                (
                    "terms_pdf_sv",
                    models.FileField(
                        upload_to="", verbose_name="swedish terms (pdf file)"
                    ),
                ),
            ],
            options={
                "verbose_name": "terms",
                "verbose_name_plural": "terms",
                "db_table": "bf_terms",
                "unique_together": {("terms_type", "effective_from")},
            },
        ),
        migrations.CreateModel(
            name="ApplicantTermsApproval",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(verbose_name="timestamp of approval"),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_terms_approval",
                        to="applications.application",
                        verbose_name="application",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user who approved the terms",
                    ),
                ),
                (
                    "selected_applicant_consents",
                    models.ManyToManyField(
                        to="terms.ApplicantConsent",
                        verbose_name="selected applicant consents",
                    ),
                ),
                (
                    "terms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="terms.terms",
                        verbose_name="terms",
                    ),
                ),
            ],
            options={
                "verbose_name": "applicant terms approval",
                "verbose_name_plural": "Applicant terms approvals",
                "db_table": "bf_applicanttermsapproval",
            },
        ),
        migrations.AddField(
            model_name="applicantconsent",
            name="terms",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_consents",
                to="terms.terms",
                verbose_name="terms",
            ),
        ),
    ]
