# Generated by Django 3.2.4 on 2021-09-17 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsOfServiceApproval",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(verbose_name="timestamp of approval"),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user who approved the terms",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_of_service_approvals",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "selected_applicant_consents",
                    models.ManyToManyField(
                        to="terms.ApplicantConsent",
                        verbose_name="selected applicant consents",
                    ),
                ),
                (
                    "terms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="terms.terms",
                        verbose_name="terms",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_of_service_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "terms of service approval",
                "verbose_name_plural": "terms of service approvals",
                "db_table": "bf_termsofserviceapproval",
                "unique_together": {("user", "company", "terms")},
            },
        ),
    ]
