# Generated by Django 3.2.4 on 2021-10-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("terms", "0002_termsofserviceapproval"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicantconsent",
            options={
                "ordering": ["ordering"],
                "verbose_name": "application consent",
                "verbose_name_plural": "application consents",
            },
        ),
        migrations.AddField(
            model_name="applicantconsent",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
    ]
