# Generated by Django 3.2.18 on 2023-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0004_alter_terms_terms_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="terms",
            name="terms_md_en",
            field=models.TextField(blank=True, verbose_name="English terms (md)"),
        ),
        migrations.AddField(
            model_name="terms",
            name="terms_md_fi",
            field=models.TextField(blank=True, verbose_name="Finnish terms (md)"),
        ),
        migrations.AddField(
            model_name="terms",
            name="terms_md_sv",
            field=models.TextField(blank=True, verbose_name="Swedish terms (md)"),
        ),
    ]
