# Generated by Django 5.2.14 on 2026-06-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0007_alter_change_terms_md_defaults_20231201_1049"),
    ]

    operations = [
        migrations.AddField(
            model_name="terms",
            name="terms_pdf_2_en",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="english terms 2 (pdf file)"
            ),
        ),
        migrations.AddField(
            model_name="terms",
            name="terms_pdf_2_fi",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="finnish terms 2 (pdf file)"
            ),
        ),
        migrations.AddField(
            model_name="terms",
            name="terms_pdf_2_sv",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="swedish terms 2 (pdf file)"
            ),
        ),
        migrations.AddField(
            model_name="terms",
            name="terms_pdf_3_en",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="english terms 3 (pdf file)"
            ),
        ),
        migrations.AddField(
            model_name="terms",
            name="terms_pdf_3_fi",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="finnish terms 3 (pdf file)"
            ),
        ),
        migrations.AddField(
            model_name="terms",
            name="terms_pdf_3_sv",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="swedish terms 3 (pdf file)"
            ),
        ),
        migrations.AddField(
            model_name="terms",
            name="terms_pdf_4_en",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="english terms 4 (pdf file)"
            ),
        ),
        migrations.AddField(
            model_name="terms",
            name="terms_pdf_4_fi",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="finnish terms 4 (pdf file)"
            ),
        ),
        migrations.AddField(
            model_name="terms",
            name="terms_pdf_4_sv",
            field=models.FileField(
                blank=True, upload_to="", verbose_name="swedish terms 4 (pdf file)"
            ),
        ),
    ]
