# Generated by Django 5.2.14 on 2026-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0008_terms_terms_pdf_2_en_terms_terms_pdf_2_fi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicantconsent",
            name="text_en",
            field=models.CharField(
                max_length=2048, verbose_name="english text for the consent checkbox"
            ),
        ),
        migrations.AlterField(
            model_name="applicantconsent",
            name="text_fi",
            field=models.CharField(
                max_length=2048, verbose_name="finnish text for the consent checkbox"
            ),
        ),
        migrations.AlterField(
            model_name="applicantconsent",
            name="text_sv",
            field=models.CharField(
                max_length=2048, verbose_name="swedish text for the consent checkbox"
            ),
        ),
    ]
