# Generated by Django 3.2.3 on 2021-06-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0002_eauthorizationprofile"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eauthorizationprofile",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="eauthorizationprofile",
            name="_company_content_type",
        ),
        migrations.RemoveField(
            model_name="eauthorizationprofile",
            name="_company_object_id",
        ),
    ]
