# Generated by Django 3.2.4 on 2021-08-20 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_log", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlogentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
    ]
