# Generated by Django 5.2.14 on 2026-05-15 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit_log", "0002_auditlogentry_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLogEntry",
        ),
    ]
