# Generated by Django 3.2.4 on 2021-10-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oidc", "0002_eauthorizationprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oidcprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="EAuthorizationProfile",
        ),
        migrations.DeleteModel(
            name="OIDCProfile",
        ),
    ]
