import pytest

from applications.enums import EmployerApplicationStatus
from applications.mock_context_service import TalpaExportMockService
from applications.models import EmployerSummerVoucher
from common.tests.factories import EmployerSummerVoucherFactory


@pytest.mark.django_db
def test_creates_all_when_none_exist():
    assert EmployerSummerVoucher.objects.unhandled().for_export().count() == 0

    created = TalpaExportMockService.ensure_talpa_export_test_applications(5)

    assert created == 5
    assert EmployerSummerVoucher.objects.unhandled().for_export().count() == 5


@pytest.mark.django_db
def test_creates_difference_when_some_exist():
    for _ in range(3):
        EmployerSummerVoucherFactory(
            application__status=EmployerApplicationStatus.SUBMITTED,
            is_exported=False,
            youth_summer_voucher__youth_application__youth_summer_voucher=None,
        )
    assert EmployerSummerVoucher.objects.unhandled().for_export().count() == 3

    created = TalpaExportMockService.ensure_talpa_export_test_applications(5)

    assert created == 2
    assert EmployerSummerVoucher.objects.unhandled().for_export().count() == 5


@pytest.mark.django_db
def test_creates_nothing_when_at_target():
    for _ in range(5):
        EmployerSummerVoucherFactory(
            application__status=EmployerApplicationStatus.SUBMITTED,
            is_exported=False,
            youth_summer_voucher__youth_application__youth_summer_voucher=None,
        )
    assert EmployerSummerVoucher.objects.unhandled().for_export().count() == 5

    created = TalpaExportMockService.ensure_talpa_export_test_applications(5)

    assert created == 0
    assert EmployerSummerVoucher.objects.unhandled().for_export().count() == 5


@pytest.mark.django_db
def test_creates_nothing_when_above_target():
    for _ in range(7):
        EmployerSummerVoucherFactory(
            application__status=EmployerApplicationStatus.SUBMITTED,
            is_exported=False,
            youth_summer_voucher__youth_application__youth_summer_voucher=None,
        )
    assert EmployerSummerVoucher.objects.unhandled().for_export().count() == 7

    created = TalpaExportMockService.ensure_talpa_export_test_applications(5)

    assert created == 0
    assert EmployerSummerVoucher.objects.unhandled().for_export().count() == 7


@pytest.mark.django_db
def test_created_names_are_labelled():
    created = TalpaExportMockService.ensure_talpa_export_test_applications(1)

    assert created == 1
    voucher = EmployerSummerVoucher.objects.first()
    assert voucher is not None
    youth_app = voucher.youth_summer_voucher.youth_application
    assert youth_app.first_name == "Autogenerated"
    assert youth_app.last_name.startswith("Talpa ")
    assert voucher.application.company.name.startswith("Autogenerated Talpa Co ")


@pytest.mark.django_db
def test_created_vouchers_appear_in_unhandled_for_export():
    created = TalpaExportMockService.ensure_talpa_export_test_applications(5)

    assert created == 5
    assert EmployerSummerVoucher.objects.unhandled().for_export().count() == 5


@pytest.mark.django_db
def test_created_company_names_are_unique():
    created = TalpaExportMockService.ensure_talpa_export_test_applications(3)

    assert created == 3
    vouchers = list(EmployerSummerVoucher.objects.all())
    company_names = [v.application.company.name for v in vouchers]
    assert len(company_names) == 3
    assert len(set(company_names)) == 3
