# Generated by Django 3.2.4 on 2021-06-16 12:01

from django.db import migrations, models
import localflavor.generic.models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deminimisaid",
            options={
                "ordering": ["application__created_at", "ordering"],
                "verbose_name": "de minimis aid",
                "verbose_name_plural": "de minimis aids",
            },
        ),
        migrations.AddField(
            model_name="applicationbasis",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="deminimisaid",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalapplicationbasis",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="historicaldeminimisaid",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="application",
            name="alternative_company_city",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="company city"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="alternative_company_postcode",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="company post code"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="alternative_company_street_address",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="company street address"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="benefit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employment_benefit", "Employment Benefit"),
                    ("salary_benefit", "Salary Benefit"),
                    ("commission_benefit", "Commission Benefit"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="co_operation_negotiations_description",
            field=models.CharField(
                blank=True,
                max_length=256,
                verbose_name="additional information about the ongoing co-operation negotiations",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="company_bank_account_number",
            field=localflavor.generic.models.IBANField(
                blank=True,
                include_countries=("FI",),
                max_length=34,
                use_nordea_extensions=False,
                verbose_name="company bank account number",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="company_contact_person_phone_number",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="company contact person's phone number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="alternative_company_city",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="company city"
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="alternative_company_postcode",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="company post code"
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="alternative_company_street_address",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="company street address"
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="benefit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employment_benefit", "Employment Benefit"),
                    ("salary_benefit", "Salary Benefit"),
                    ("commission_benefit", "Commission Benefit"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="co_operation_negotiations_description",
            field=models.CharField(
                blank=True,
                max_length=256,
                verbose_name="additional information about the ongoing co-operation negotiations",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="company_bank_account_number",
            field=localflavor.generic.models.IBANField(
                blank=True,
                include_countries=("FI",),
                max_length=34,
                use_nordea_extensions=False,
                verbose_name="company bank account number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="company_contact_person_phone_number",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="company contact person's phone number",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deminimisaid",
            unique_together={("application", "ordering")},
        ),
    ]
