# Generated by Django 3.2.4 on 2021-06-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_validation_fixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_living_in_helsinki",
            field=models.BooleanField(
                default=False, verbose_name="is living in helsinki"
            ),
        ),
    ]
