# Generated by Django 3.2.4 on 2021-07-01 06:49

from django.db import migrations, models
import encrypted_fields.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_employee_is_living_in_helsinki"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="application_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="commission_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="amount of the commission (eur)",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="commission_description",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Description of the commission"
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="application_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_language",
            field=models.CharField(
                blank=True,
                choices=[("fi", "suomi"), ("sv", "svenska"), ("en", "english")],
                default="fi",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="social_security_number",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=11, verbose_name="social security number"
            ),
        ),
    ]
