# Generated by Django 3.2.4 on 2021-07-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_field_changes_for_employee_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="additional_pay_subsidy_percent",
            field=models.IntegerField(
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                null=True,
                verbose_name="Pay subsidy percent for second pay subsidy grant",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="pay_subsidy_granted",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="pay_subsidy_percent",
            field=models.IntegerField(
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                null=True,
                verbose_name="Pay subsidy percent",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="additional_pay_subsidy_percent",
            field=models.IntegerField(
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                null=True,
                verbose_name="Pay subsidy percent for second pay subsidy grant",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="pay_subsidy_granted",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="pay_subsidy_percent",
            field=models.IntegerField(
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                null=True,
                verbose_name="Pay subsidy percent",
            ),
        ),
    ]
