# Generated by Django 3.2.4 on 2021-07-02 10:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_application_page2_new_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("employment_contract", "employment contract"),
                            ("pay_subsidy_decision", "pay subsidy decision"),
                            ("commission_contract", "commission contract"),
                            (
                                "education_contract",
                                "education contract of the apprenticeship office",
                            ),
                            ("helsinki_benefit_voucher", "helsinki benefit voucher"),
                        ],
                        max_length=64,
                        verbose_name="attachment type in business rules",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("application/pdf", "pdf"),
                            ("image/png", "png"),
                            ("image/jpeg", "jpeg"),
                        ],
                        max_length=100,
                        verbose_name="technical content type of the attachment",
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
                (
                    "attachment_file",
                    models.FileField(
                        upload_to="", verbose_name="application attachment content"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="applications.application",
                        verbose_name="application",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
                "db_table": "bf_applications_attachment",
                "ordering": ["application__created_at", "ordering"],
                "unique_together": {("application", "ordering")},
            },
        ),
    ]
