# Generated by Django 3.2.4 on 2021-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_attachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "ordering": [
                    "application__created_at",
                    "attachment_type",
                    "created_at",
                ],
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
            },
        ),
        migrations.AlterField(
            model_name="application",
            name="additional_pay_subsidy_percent",
            field=models.IntegerField(
                blank=True,
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                null=True,
                verbose_name="Pay subsidy percent for second pay subsidy grant",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="application_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="pay_subsidy_percent",
            field=models.IntegerField(
                blank=True,
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                null=True,
                verbose_name="Pay subsidy percent",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="additional_pay_subsidy_percent",
            field=models.IntegerField(
                blank=True,
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                null=True,
                verbose_name="Pay subsidy percent for second pay subsidy grant",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="application_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="pay_subsidy_percent",
            field=models.IntegerField(
                blank=True,
                choices=[(30, "30%"), (40, "40%"), (50, "50%"), (100, "100%")],
                null=True,
                verbose_name="Pay subsidy percent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attachment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="attachment",
            name="ordering",
        ),
    ]
