# Generated by Django 3.2.4 on 2021-07-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_attachments_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="company_contact_person_first_name",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="company_contact_person_last_name",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="company_contact_person_first_name",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="company_contact_person_last_name",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="last name"
            ),
        ),
    ]
