# Generated by Django 3.2.4 on 2021-08-11 16:21

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_create_application_number_seq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_number",
            field=models.IntegerField(
                default=applications.models._get_next_application_number,
                verbose_name="application number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="application_number",
            field=models.IntegerField(
                default=applications.models._get_next_application_number,
                verbose_name="application number",
            ),
        ),
    ]
