# Generated by Django 3.2.4 on 2021-08-20 06:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("applications", "0013_application_number_auto_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationBatch",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            (
                                "awaiting_ahjo_decision",
                                "Sent to Ahjo, decision pending",
                            ),
                            ("decided", "Decided"),
                            ("returned", "Returned"),
                            ("sent_to_talpa", "Sent to Talpa"),
                            ("completed", "Processing is completed"),
                        ],
                        default="draft",
                        max_length=64,
                        verbose_name="status of batch",
                    ),
                ),
                (
                    "proposal_for_decision",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                        max_length=64,
                        verbose_name="proposal for decision",
                    ),
                ),
                (
                    "decision_maker_title",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="decision maker's title in Ahjo",
                    ),
                ),
                (
                    "decision_maker_name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="decision maker's name in Ahjo",
                    ),
                ),
                (
                    "section_of_the_law",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        verbose_name="section of the law in Ahjo decision",
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="date of the decision in Ahjo",
                    ),
                ),
                (
                    "expert_inspector_name",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        verbose_name="Expert inspector's name",
                    ),
                ),
                (
                    "expert_inspector_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Expert inspector's email address",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_batches",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
            ],
            options={
                "verbose_name": "application batch",
                "verbose_name_plural": "application batches",
                "db_table": "bf_applicationbatch",
            },
        ),
        migrations.AddField(
            model_name="application",
            name="batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="applications.applicationbatch",
                verbose_name="ahjo batch",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="applications.applicationbatch",
                verbose_name="ahjo batch",
            ),
        ),
    ]
