# Generated by Django 3.2.4 on 2021-08-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_application_batch_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="calculated_benefit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="amount of the benefit granted, calculated by the systems",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="manual_benefit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="amount of the benefit manually entered by the application handler",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="calculated_benefit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="amount of the benefit granted, calculated by the system",
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="manual_benefit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="amount of the benefit manually entered by the application handler",
            ),
        ),
    ]
