# Generated by Django 3.2.4 on 2021-09-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0016_benefit_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="company_department",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="company department"
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="company_department",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="company department"
            ),
        ),
    ]
