# Generated by Django 3.2.4 on 2021-09-07 11:30

from django.db import migrations
from django.conf import settings
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0017_add_company_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="social_security_number",
        ),
    ]
