# Generated by Django 3.2.4 on 2021-09-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0019_searchable_social_security_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("employment_contract", "employment contract"),
                    ("pay_subsidy_decision", "pay subsidy decision"),
                    ("commission_contract", "commission contract"),
                    (
                        "education_contract",
                        "education contract of the apprenticeship office",
                    ),
                    ("helsinki_benefit_voucher", "helsinki benefit voucher"),
                    ("employee_consent", "helsinki benefit voucher"),
                ],
                max_length=64,
                verbose_name="attachment type in business rules",
            ),
        ),
    ]
