# Generated by Django 3.2.4 on 2021-09-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0022_add_association_immediate_manager_check"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="calculated_benefit_amount",
        ),
        migrations.RemoveField(
            model_name="application",
            name="manual_benefit_amount",
        ),
        migrations.RemoveField(
            model_name="historicalapplication",
            name="calculated_benefit_amount",
        ),
        migrations.RemoveField(
            model_name="historicalapplication",
            name="manual_benefit_amount",
        ),
    ]
