# Generated by Django 3.2.4 on 2021-10-20 13:34

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0023_move_benefit_amount_to_calculation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="company_contact_person_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=3),
                    django.core.validators.MaxLengthValidator(limit_value=13),
                ],
                verbose_name="company contact person's phone number",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=3),
                    django.core.validators.MaxLengthValidator(limit_value=13),
                ],
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="company_contact_person_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                region=None,
                validators=[
                    django.core.validators.MinLengthValidator(limit_value=3),
                    django.core.validators.MaxLengthValidator(limit_value=13),
                ],
                verbose_name="company contact person's phone number",
            ),
        ),
    ]
