# Generated by Django 3.2.4 on 2021-12-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0026_alter_applicationbatch_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationlogentry",
            options={
                "ordering": ["application__created_at", "created_at"],
                "verbose_name": "application log entry",
                "verbose_name_plural": "application log entries",
            },
        ),
    ]
