# Generated by Django 3.2.18 on 2023-03-29 09:41

from django.db import migrations
from django.conf import settings
import encrypted_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0029_history_date_format_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="encrypted_first_name",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=128, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="encrypted_last_name",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, max_length=128, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=encrypted_fields.fields.SearchField(
                blank=True,
                db_index=True,
                encrypted_field_name="encrypted_first_name",
                hash_key=settings.EMPLOYEE_FIRST_NAME_HASH_KEY,
                max_length=66,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=encrypted_fields.fields.SearchField(
                blank=True,
                db_index=True,
                encrypted_field_name="encrypted_last_name",
                hash_key=settings.EMPLOYEE_LAST_NAME_HASH_KEY,
                max_length=66,
                null=True,
            ),
        ),
    ]
