# Generated by Django 3.2.18 on 2023-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_encrypt_employee_first_name_and_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_origin',
            field=models.CharField(choices=[('handler', 'Handler'), ('applicant', 'Applicant')], default='applicant', max_length=64, verbose_name='application origin'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='application_origin',
            field=models.CharField(choices=[('handler', 'Handler'), ('applicant', 'Applicant')], default='applicant', max_length=64, verbose_name='application origin'),
        ),
    ]
