# Generated by Django 3.2.18 on 2023-05-26 07:30

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_application_batches_expert_inspector_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_origin',
            field=models.CharField(choices=[('handler', 'Handler'), ('applicant', 'Applicant')], default='applicant', max_length=64, verbose_name='application origin'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='application_origin',
            field=models.CharField(choices=[('handler', 'Handler'), ('applicant', 'Applicant')], default='applicant', max_length=64, verbose_name='application origin'),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='decision_date',
            field=models.DateField(blank=True, null=True, validators=[applications.models.validate_decision_date], verbose_name='date of the decision in Ahjo'),
        ),
    ]
