# Generated by Django 3.2.18 on 2023-08-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0037_reviewstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstate',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='approval'),
        ),
    ]
