# Generated by Django 3.2.18 on 2023-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0039_alter_paysubsidy_percentages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pay_subsidy_granted',
            field=models.CharField(blank=True, choices=[('aged', 'aged'), ('default', 'default'), ('none', 'none')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='pay_subsidy_granted',
            field=models.CharField(blank=True, choices=[('aged', 'aged'), ('default', 'default'), ('none', 'none')], max_length=128, null=True),
        ),
    ]
