# Generated by Django 3.2.18 on 2023-09-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0040_pay_subsidy_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='paper_application_date',
            field=models.DateField(blank=True, null=True, verbose_name='paper application date'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='paper_application_date',
            field=models.DateField(blank=True, null=True, verbose_name='paper application date'),
        ),
    ]
