# Generated by Django 3.2.18 on 2023-09-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0040_pay_subsidy_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhjoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
