# Generated by Django 3.2.18 on 2023-09-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0040_alter_pay_subsidy_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='pay_subsidy_granted',
            field=models.CharField(blank=True, choices=[('granted', 'Pay subsidy granted (default)'), ('granted_aged', 'Pay subsidy granted (aged)'), ('not_granted', 'No granted pay subsidy')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='pay_subsidy_granted',
            field=models.CharField(blank=True, choices=[('granted', 'Pay subsidy granted (default)'), ('granted_aged', 'Pay subsidy granted (aged)'), ('not_granted', 'No granted pay subsidy')], max_length=128, null=True),
        ),
    ]
