# Generated by Django 3.2.18 on 2023-10-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_add_paper_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstate',
            name='paper',
            field=models.BooleanField(default=False, verbose_name='paper'),
        ),
    ]
