# Generated by Django 3.2.18 on 2023-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0045_alter_ahjostatus_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="ahjo_case_guid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="ahjo_case_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="ahjo_case_guid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="ahjo_case_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
