# Generated by Django 3.2.18 on 2023-11-24 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0046_add_ahjo_ids_to_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationGeneratedFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('application/pdf', 'pdf'), ('image/png', 'png'), ('image/jpeg', 'jpeg')], max_length=100, verbose_name='technical content type of the attachment')),
                ('generated_file', models.FileField(upload_to='', verbose_name='application generated file content')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='applications.application', verbose_name='application')),
            ],
            options={
                'verbose_name': 'generated_file',
                'verbose_name_plural': 'generated_files',
                'db_table': 'bf_applications_generated_file',
                'ordering': ['application__created_at', 'created_at'],
            },
        ),
    ]
