# Generated by Django 3.2.23 on 2023-12-28 21:40

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("applications", "0052_application_talpa_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalAttachment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="time modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("employment_contract", "employment contract"),
                            ("pay_subsidy_decision", "pay subsidy decision"),
                            ("commission_contract", "commission contract"),
                            (
                                "education_contract",
                                "education contract of the apprenticeship office",
                            ),
                            ("helsinki_benefit_voucher", "helsinki benefit voucher"),
                            ("employee_consent", "employee consent"),
                            ("full_application", "full application"),
                            ("other_attachment", "other attachment"),
                        ],
                        max_length=64,
                        verbose_name="attachment type in business rules",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("application/pdf", "pdf"),
                            ("image/png", "png"),
                            ("image/jpeg", "jpeg"),
                        ],
                        max_length=100,
                        verbose_name="technical content type of the attachment",
                    ),
                ),
                (
                    "attachment_file",
                    models.TextField(
                        max_length=100, verbose_name="application attachment content"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="applications.application",
                        verbose_name="application",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical attachment",
                "verbose_name_plural": "historical attachments",
                "db_table": "bf_applications_attachment_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
