# Generated by Django 3.2.23 on 2024-01-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0054_alter_historicalattachment_attachment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="ahjo_hash_value",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="ahjo_version_series_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachment",
            name="ahjo_hash_value",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachment",
            name="ahjo_version_series_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
