# Generated by Django 3.2.23 on 2024-02-14 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0055_add_attachment_version_id_and_hash_20240131_1620"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionProposalTemplateSection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="time created"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="time modified"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            (
                                "decision_section",
                                "Template part for the decision section of a application decision proposal",
                            ),
                            (
                                "justification_section",
                                "Template part for the decision justification section of a decision proposal",
                            ),
                        ],
                        default="decision_section",
                        max_length=64,
                        verbose_name="type of the decision proposal template section",
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("accepted_decision", "An accepted decision"),
                            ("denied_decision", "A denied decision"),
                        ],
                        default="accepted_decision",
                        max_length=64,
                        verbose_name="type of the decision",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("fi", "suomi"), ("sv", "svenska"), ("en", "english")],
                        default="fi",
                        max_length=2,
                    ),
                ),
                (
                    "template_text",
                    models.TextField(
                        verbose_name="decision proposal section text content"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256,
                        verbose_name="name of the decision proposal template section",
                    ),
                ),
            ],
            options={
                "verbose_name": "decision proposal template section",
                "verbose_name_plural": "decision proposal template sections",
                "db_table": "bf_applications_decision_proposal_template_section",
            },
        ),
    ]
