# Generated by Django 3.2.23 on 2024-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0059_applicationalteration"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationalteration",
            name="state",
            field=models.TextField(
                choices=[
                    ("received", "Received"),
                    ("opened", "Opened"),
                    ("handled", "Handled"),
                ],
                default="received",
                verbose_name="state of alteration",
            ),
        ),
    ]
