# Generated by Django 3.2.23 on 2024-03-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0060_applicationalteration_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicationalteration",
            old_name="use_alternate_einvoice_provider",
            new_name="use_einvoice",
        ),
        migrations.AlterField(
            model_name="applicationalteration",
            name="reason",
            field=models.TextField(blank=True, verbose_name="reason for alteration"),
        ),
        migrations.AlterField(
            model_name="applicationalteration",
            name="use_einvoice",
            field=models.BooleanField(
                default=False,
                verbose_name="whether to use handle billing with an e-invoice instead of a bill sent to a physical address",
            ),
        ),
        migrations.AddField(
            model_name="applicationalteration",
            name="contact_person_name",
            field=models.TextField(verbose_name="contact person"),
        ),
    ]
