# Generated by Django 3.2.23 on 2024-04-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0062_alter_applicationalteration_recovery_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="decisionproposaltemplatesection",
            options={
                "verbose_name": "Ahjo decision text template",
                "verbose_name_plural": "Ahjo decision text templates",
            },
        ),
        migrations.RemoveField(
            model_name="decisionproposaltemplatesection",
            name="section_type",
        ),
        migrations.RemoveField(
            model_name="decisionproposaltemplatesection",
            name="template_text",
        ),
        migrations.AddField(
            model_name="decisionproposaltemplatesection",
            name="template_decision_text",
            field=models.TextField(null=True, verbose_name="Proposal text, decision"),
        ),
        migrations.AddField(
            model_name="decisionproposaltemplatesection",
            name="template_justification_text",
            field=models.TextField(
                null=True, verbose_name="Proposal text, justification"
            ),
        ),
        migrations.AlterField(
            model_name="decisionproposaltemplatesection",
            name="name",
            field=models.CharField(
                max_length=256, verbose_name="name of the decision text template"
            ),
        ),
    ]
