# Generated by Django 3.2.23 on 2024-04-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0067_add_handler_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationbatch',
            name='auto_generated_by_ahjo',
            field=models.BooleanField(blank=True, default=False, verbose_name='Batch created through Ahjo integration'),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='decision_maker_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="decision maker's name in Ahjo"),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='decision_maker_title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="decision maker's title in Ahjo"),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='expert_inspector_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Expert inspector's email address"),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='expert_inspector_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Expert inspector's name"),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='expert_inspector_title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Expert inspector's title"),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='p2p_checker_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="P2P acceptor's title"),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='p2p_inspector_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="P2P inspector's email address"),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='p2p_inspector_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="P2P inspector's name"),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='proposal_for_decision',
            field=models.CharField(blank=True, choices=[('accepted', 'Decided Accepted'), ('rejected', 'Decided Rejected')], max_length=64, null=True, verbose_name='proposal for decision'),
        ),
        migrations.AlterField(
            model_name='applicationbatch',
            name='section_of_the_law',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='section of the law in Ahjo decision'),
        ),
    ]
