# Generated by Django 3.2.23 on 2024-05-08 06:47

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0071_auto_20240507_0226"),
    ]
    operations = [TrigramExtension()]
