# Generated by Django 4.2.11 on 2024-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0073_alter_ahjostatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="ahjo_case_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="ahjo_case_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
