# Generated by Django 4.2.11 on 2024-06-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0074_auto_20240606_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="handled_by_ahjo_automation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="handled_by_ahjo_automation",
            field=models.BooleanField(default=False),
        ),
    ]
