# Generated by Django 4.2.11 on 2024-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0075_application_handled_by_ahjo_automation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    (
                        "exported_ahjo_report",
                        "Ahjo report created, not yet sent to AHJO",
                    ),
                    ("awaiting_ahjo_decision", "Sent to Ahjo, decision pending"),
                    ("accepted", "Accepted in Ahjo"),
                    ("rejected", "Rejected in Ahjo"),
                    ("returned", "Returned from Ahjo without decision"),
                    ("sent_to_talpa", "Sent to Talpa"),
                    ("completed", "Processing is completed"),
                    ("rejected_by_talpa", "Rejected by Talpa"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=64,
                verbose_name="status of batch",
            ),
        ),
    ]
