# Generated by Django 4.2.11 on 2024-08-01 10:09

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0076_alter_applicationbatch_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="attachment_file",
            field=models.FileField(
                upload_to=applications.models.cleanup_filename,
                verbose_name="application attachment content",
            ),
        ),
    ]
