# Generated by Django 4.2.11 on 2024-08-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0077_alter_attachment_attachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="ahjostatus",
            name="error_from_ahjo",
            field=models.JSONField(null=True),
        ),
    ]
