# Generated by Django 4.2.11 on 2024-08-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0078_ahjostatus_error_from_ahjo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ahjostatus",
            name="error_from_ahjo",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
