# Generated by Django 4.2.11 on 2024-08-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0079_alter_ahjostatus_error_from_ahjo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("application/pdf", "pdf"),
                    ("image/png", "png"),
                    ("image/jpeg", "jpeg"),
                    ("application/xml", "xml"),
                ],
                max_length=100,
                verbose_name="technical content type of the attachment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalattachment",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("application/pdf", "pdf"),
                    ("image/png", "png"),
                    ("image/jpeg", "jpeg"),
                    ("application/xml", "xml"),
                ],
                max_length=100,
                verbose_name="technical content type of the attachment",
            ),
        ),
    ]
