# Generated by Django 4.2.11 on 2024-08-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0080_alter_attachment_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ahjodecisiontext",
            name="decision_maker_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="the ID of the decision maker",
            ),
        ),
        migrations.AddField(
            model_name="ahjodecisiontext",
            name="decision_maker_name",
            field=models.TextField(
                blank=True, null=True, verbose_name="the name of the decision maker"
            ),
        ),
    ]
