# Generated by Django 4.2.11 on 2024-09-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0081_ahjodecisiontext_decision_maker_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ahjodecisionproposaldraft",
            name="decision_maker_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="the ID of the decision maker",
            ),
        ),
        migrations.AddField(
            model_name="ahjodecisionproposaldraft",
            name="decision_maker_name",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="the name of the decision maker role",
            ),
        ),
    ]
