# Generated by Django 4.2.11 on 2024-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0082_ahjodecisionproposaldraft_decision_maker_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ahjostatus",
            name="ahjo_request_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
