# Generated by Django 4.2.11 on 2024-10-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0084_ahjostatus_validation_error_from_ahjo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ahjostatus",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "submitted_but_not_sent_to_ahjo",
                        "Submitted but not sent to AHJO",
                    ),
                    (
                        "request_to_open_case_sent",
                        "Request to open the case sent to AHJO",
                    ),
                    ("case_opened", "Case opened in AHJO"),
                    ("update_request_sent", "Update request sent"),
                    ("update_request_received", "Update request received"),
                    ("decision_proposal_sent", "Decision proposal sent"),
                    ("decision_proposal_accepted", "Decision proposal accepted"),
                    ("decision_proposal_rejected", "Decision proposal rejected"),
                    ("scheduled_for_deletion", "Scheduled for deletion"),
                    ("delete_request_sent", "Delete request sent"),
                    ("delete_request_received", "Delete request received"),
                    ("new_record_request_sent", "New record request sent"),
                    ("new_record_received", "New record received by Ahjo"),
                    ("removed", "Decision cancelled in Ahjo"),
                    ("signed", "Decision signed and completed in Ahjo"),
                    ("updated", "Decision updated in Ahjo"),
                    ("decision_details_request_sent", "Decision details request sent"),
                    ("details_received", "Decision details received from Ahjo"),
                ],
                default="submitted_but_not_sent_to_ahjo",
                max_length=64,
                verbose_name="status",
            ),
        ),
    ]
