# Generated by Django 4.2.11 on 2024-11-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0086_alter_ahjodecisionproposaldraft_handler_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ahjodecisionproposaldraft",
            name="handler_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("handler", "Helsinki-benefit handler"),
                    ("manager", "Team manager"),
                ],
                max_length=64,
                null=True,
                verbose_name=(
                    "Handler role (DEPRECATED, was used before dynamic fetch of"
                    " decision makers)"
                ),
            ),
        ),
    ]
