# Generated by Django 4.2.11 on 2024-11-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0087_alter_ahjodecisionproposaldraft_handler_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="ahjodecisiontext",
            name="signer_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="the ID of the signer",
            ),
        ),
        migrations.AddField(
            model_name="ahjodecisiontext",
            name="signer_name",
            field=models.TextField(
                blank=True, null=True, verbose_name="the name of the signer"
            ),
        ),
    ]
