# Generated by Django 4.2.11 on 2024-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0089_ahjodecisionproposaldraft_signer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="talpa_status",
            field=models.CharField(
                choices=[
                    ("not_sent_to_talpa", "Not sent to Talpa"),
                    ("rejected_by_talpa", "Rejected by Talpa"),
                    ("partially_sent_to_talpa", "One of two instalments sent to Talpa"),
                    ("successfully_sent_to_talpa", "Successfully sent to Talpa"),
                ],
                default="not_sent_to_talpa",
                max_length=64,
                verbose_name="talpa_status",
            ),
        ),
        migrations.AlterField(
            model_name="applicationbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    (
                        "exported_ahjo_report",
                        "Ahjo report created, not yet sent to AHJO",
                    ),
                    ("awaiting_ahjo_decision", "Sent to Ahjo, decision pending"),
                    ("accepted", "Accepted in Ahjo"),
                    ("rejected", "Rejected in Ahjo"),
                    ("returned", "Returned from Ahjo without decision"),
                    ("sent_to_talpa", "Sent to Talpa"),
                    ("partially_sent_to_talpa", "One of two instalments sent to Talpa"),
                    ("completed", "Processing is completed"),
                    ("rejected_by_talpa", "Rejected by Talpa"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=64,
                verbose_name="status of batch",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapplication",
            name="talpa_status",
            field=models.CharField(
                choices=[
                    ("not_sent_to_talpa", "Not sent to Talpa"),
                    ("rejected_by_talpa", "Rejected by Talpa"),
                    ("partially_sent_to_talpa", "One of two instalments sent to Talpa"),
                    ("successfully_sent_to_talpa", "Successfully sent to Talpa"),
                ],
                default="not_sent_to_talpa",
                max_length=64,
                verbose_name="talpa_status",
            ),
        ),
    ]
