# Generated by Django 5.2.12 on 2026-03-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0090_alter_application_talpa_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="employer_assurance",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="employer_assurance",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("employment_contract", "employment contract"),
                    ("pay_subsidy_decision", "pay subsidy decision"),
                    ("commission_contract", "commission contract"),
                    (
                        "education_contract",
                        "education contract of the apprenticeship office",
                    ),
                    ("helsinki_benefit_voucher", "helsinki benefit voucher"),
                    ("employee_consent", "employee consent"),
                    ("payslip", "payslip"),
                    ("full_application", "full application"),
                    ("other_attachment", "other attachment"),
                    ("pdf_summary", "pdf summary"),
                    ("decision_text_xml", "public decision text xml attachment"),
                    (
                        "decision_text_secret_xml",
                        "non-public decision text xml attachment",
                    ),
                ],
                max_length=64,
                verbose_name="attachment type in business rules",
            ),
        ),
        migrations.AlterField(
            model_name="historicalattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("employment_contract", "employment contract"),
                    ("pay_subsidy_decision", "pay subsidy decision"),
                    ("commission_contract", "commission contract"),
                    (
                        "education_contract",
                        "education contract of the apprenticeship office",
                    ),
                    ("helsinki_benefit_voucher", "helsinki benefit voucher"),
                    ("employee_consent", "employee consent"),
                    ("payslip", "payslip"),
                    ("full_application", "full application"),
                    ("other_attachment", "other attachment"),
                    ("pdf_summary", "pdf summary"),
                    ("decision_text_xml", "public decision text xml attachment"),
                    (
                        "decision_text_secret_xml",
                        "non-public decision text xml attachment",
                    ),
                ],
                max_length=64,
                verbose_name="attachment type in business rules",
            ),
        ),
    ]
