# Generated by Django 5.2.12 on 2026-04-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0091_add_de_minimis_grant_send_to_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer_assurance',
            field=models.BooleanField(null=True, verbose_name='employer assurance'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='employer_assurance',
            field=models.BooleanField(null=True, verbose_name='employer assurance'),
        ),
    ]
