# Generated by Django 5.2.13 on 2026-05-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0093_alter_attachment_attachment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="company_number_of_employees",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="number of employees"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="employer_business_brief",
            field=models.TextField(blank=True, verbose_name="employer business brief"),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="company_number_of_employees",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="number of employees"
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="employer_business_brief",
            field=models.TextField(blank=True, verbose_name="employer business brief"),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("employment_contract", "employment contract"),
                    ("pay_subsidy_decision", "pay subsidy decision"),
                    ("commission_contract", "commission contract"),
                    (
                        "education_contract",
                        "education contract of the apprenticeship office",
                    ),
                    ("helsinki_benefit_voucher", "helsinki benefit voucher"),
                    ("employee_consent", "employee consent"),
                    ("full_application", "full application"),
                    ("other_attachment", "other attachment"),
                    ("pdf_summary", "pdf summary"),
                    ("decision_text_xml", "public decision text xml attachment"),
                    (
                        "decision_text_secret_xml",
                        "non-public decision text xml attachment",
                    ),
                    ("payslip", "payslip"),
                    ("business_brief", "business brief"),
                ],
                max_length=64,
                verbose_name="attachment type in business rules",
            ),
        ),
        migrations.AlterField(
            model_name="historicalattachment",
            name="attachment_type",
            field=models.CharField(
                choices=[
                    ("employment_contract", "employment contract"),
                    ("pay_subsidy_decision", "pay subsidy decision"),
                    ("commission_contract", "commission contract"),
                    (
                        "education_contract",
                        "education contract of the apprenticeship office",
                    ),
                    ("helsinki_benefit_voucher", "helsinki benefit voucher"),
                    ("employee_consent", "employee consent"),
                    ("full_application", "full application"),
                    ("other_attachment", "other attachment"),
                    ("pdf_summary", "pdf summary"),
                    ("decision_text_xml", "public decision text xml attachment"),
                    (
                        "decision_text_secret_xml",
                        "non-public decision text xml attachment",
                    ),
                    ("payslip", "payslip"),
                    ("business_brief", "business brief"),
                ],
                max_length=64,
                verbose_name="attachment type in business rules",
            ),
        ),
    ]
