# Generated by Django 5.2.14 on 2026-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0094_application_company_business_brief_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="purchased_service",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="purchased service"
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="purchased_service",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="purchased service"
            ),
        ),
    ]
