# Generated by Django 5.2.13 on 2026-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0094_application_company_number_of_employees_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="employer_business_brief",
        ),
        migrations.RemoveField(
            model_name="historicalapplication",
            name="employer_business_brief",
        ),
        migrations.AddField(
            model_name="application",
            name="company_business_brief",
            field=models.TextField(blank=True, verbose_name="company business brief"),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="company_business_brief",
            field=models.TextField(blank=True, verbose_name="company business brief"),
        ),
    ]
