# Generated by Django 5.2.14 on 2026-06-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0095_application_purchased_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="other_subsidised_employed",
            field=models.BooleanField(
                null=True, verbose_name="other subsidised employed"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="other_subsidised_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="number of subsidised employees"
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="other_subsidised_employed",
            field=models.BooleanField(
                null=True, verbose_name="other subsidised employed"
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="other_subsidised_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="number of subsidised employees"
            ),
        ),
    ]
