# Generated by Django 5.2.14 on 2026-05-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0095_remove_application_employer_business_brief_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="other_financial_support_for_employment",
            field=models.BooleanField(
                null=True, verbose_name="other financial support for employment"
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="other_financial_support_for_employment",
            field=models.BooleanField(
                null=True, verbose_name="other financial support for employment"
            ),
        ),
    ]
