# Generated by Django 5.2.14 on 2026-05-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "applications",
            "0096_application_other_financial_support_for_employment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="role_of_employee_in_organization",
            field=models.TextField(
                blank=True, verbose_name="role of employee in organization"
            ),
        ),
        migrations.AddField(
            model_name="historicalapplication",
            name="role_of_employee_in_organization",
            field=models.TextField(
                blank=True, verbose_name="role of employee in organization"
            ),
        ),
    ]
