name: (KS) Backend CI

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '.github/workflows/ks-backend-ci.yml'
      - '.pre-commit-config.yaml'
      - 'backend/kesaseteli/**'
      - 'backend/shared/**'
  workflow_dispatch:

jobs:
  common:
    uses: City-of-Helsinki/.github/.github/workflows/ci-django-api.yml@main
    secrets: inherit
    with:
      python-version: 3.12
      postgres-major-version: 17
      working-directory: ./backend/kesaseteli
      extra-commands: |
        echo 'DEBUG=1' >> .env.kesaseteli-backend
        echo 'ENCRYPTION_KEY=f164ec6bd6fbc4aef5647abc15199da0f9badcc1d2127bde2087ae0d794a9a0b' >> .env.kesaseteli-backend
        echo 'SOCIAL_SECURITY_NUMBER_HASH_KEY=ee235e39ebc238035a6264c063dd829d4b6d2270604b57ee1f463e676ec44669' >> .env.kesaseteli-backend

        sudo apt-get install xmlsec1 libsasl2-dev libssl-dev
