name: (KS) Python coding style

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '.github/workflows/ks-py-coding-style.yml'
      - 'backend/kesaseteli/**'
      - 'backend/shared/**'
  workflow_dispatch:

env:
  DEBUG: 1

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Run pre-commit (kesaseteli)
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: --files backend/kesaseteli/**
    - name: Run pre-commit (shared)
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: --files backend/shared/**
